### ISSUE TITLE
Feature Request - Better Quest Support

### ISSUE THREAD

**Issue by behub-torch** [Tercioo/Plater-Nameplates#10]
I know you've got a basic mod over at wago, which in a recent update seems to of stopped working.

Was hoping for something more detailed (and pretty!) such as the one developed for ElvUI's nameplates here:
https://git.tukui.org/elvui/elvui/blob/development/ElvUI/Modules/Nameplates/Plugins/QuestIcons.lua

Another example, but less detailed is QuestPlates:
https://www.curseforge.com/wow/addons/questplates

Both these plugins/addons use tooltip scanning and iterate through the quest log.

I did attempt to write a plugin/mod for Plater, but tooltip scanning is not something I have worked with before.

**Comment by cont1nuity** [comment]
If you could add some screenshots to explain what you're expecting would be great.
I think I get the idea, but having a bit more input would be great.

**Comment by behub** [comment]
Using ElvUI's implementation for example where the progress of a quest is shown to the right and the icon represents the type of objective ..

So a quest with a kill objective shows up like this:
![image](https://user-images.githubusercontent.com/870239/56496773-297dd180-653e-11e9-8d02-219c98d5c733.png)

A quest to complete a task 6 times:
![image](https://user-images.githubusercontent.com/870239/56496797-44e8dc80-653e-11e9-823d-9e71685120e3.png)

**Comment by cont1nuity** [comment]
I think we can add this to the todo list. It is a bit more tricky to get the actual quest amount information (tooltip scanning) than I initially thought, but we will see.

**Comment by cont1nuity** [comment]
I created a small mod as a basic implementation of this feature: https://wago.io/uwe9CEwMm
Depending on my spare time I might look into enhancing this mod or Plater to enhance this feature.

**Comment by behub** [comment]
I shall import it and check it out ! Thanks
