### ISSUE TITLE
[Feature Request] show friendly class icons without nameplates

### ISSUE THREAD

**Issue by ujellyx** [Tercioo/Plater-Nameplates#102]
In ThreatPlates one can configure a "headline view" that allows for showing the class icon and name above friendlies while still having the option to configure separate enemy nameplates.

Here is an example:
![2021-06-15 18_05_58-WoWScrnShot_061521_180430 jpg - IrfanView](https://user-images.githubusercontent.com/17804807/122087115-ac400580-ce04-11eb-8a01-c3eb344dc6f2.png)

I've gone through all the settings and tried various things, but can't seem to replicate it this way in Plater.
Therefore I'd like to request a feature like that.

**Comment by cont1nuity** [comment]
There are several class and spec icon indicator mods on wago.io, there is no need to have this as a  core feature.
