### ISSUE TITLE
Extra Button

### ISSUE THREAD

**Issue by vandiel01** [Tercioo/Plater-Nameplates#103]
Latest from Wowup

Anytime there is Extra Button appears from ANYTHING, it would be pushed DOWN and overlap the actionbar.  I did fstack and it keep showing "NamePlatexxPlaterUnitFrame" in background.  I need to check and see if that's the cause?

![image](https://user-images.githubusercontent.com/52209920/126559653-e316e587-bf9a-4ed5-88b1-62663f0c0eaf.png)

**Comment by cont1nuity** [comment]
Have you tried this without Plater? I have a similar fstack and no issues at all.

**Comment by vandiel01** [comment]
It appears to be TitanPanel related (I suspected after it was updated)... Can consider this closed for the moment.. Thanks for your patience while I waited for someone to release update from another addon.
