### ISSUE TITLE
Feature Request - Option to display personal power bar in numeric values

### ISSUE THREAD

**Issue by Thex-PiedDroit** [Tercioo/Plater-Nameplates#106]
Hi there!
I have searched for a while in the settings and haven't found this, so i'm assuming it's not implemented, but i would love to be able to have numerical values displayed in the personal power bar, in addition to the percent value, if possible :)

Have a wonderful day!

**Comment by cont1nuity** [comment]
There are mods for this on wago.io  which can be used.
