### ISSUE TITLE
(Feature Request) Option to keep Blizzards' nameplates

### ISSUE THREAD

**Issue by ars4l4n** [Tercioo/Plater-Nameplates#108]
## Game Version:
TBC Classic 2.5.2.41446

## Suggestion:
I'd like a function to show large debuffs above the enemy nameplate while at the same time keeping the looks of Blizzards' default nameplates.

## My Attempts to tackle the issue:
I tried to look for other addons to achieve this, eg BigDebuff but the latter was missing some relevant Debuff spells. I tried configuring Platers' own plates for a more default-like look too, but would be happier with the original.

**Comment by cont1nuity** [comment]
All visualization / styles can be changed via configuration and modding. Iirc there is a default style profile on wago.io already.

Plater either has a module enabled or disabled, there won't be anything in between.
