### ISSUE TITLE
Interrupt lockdown duration as a special buff

### ISSUE THREAD

**Issue by tharakadesilva** [Tercioo/Plater-Nameplates#109]
**Game and Plater version**
Which is the game version and Plater version you're using.

- Game version: 9.1.5.42010
- Plater version: 343-Retail

**Describe the feature request**

I want to see the interrupt lockdown duration as a special buff.

This is similar to the feature provided by [BigDebuffs](https://www.curseforge.com/wow/addons/bigdebuffs).

**Screenshots**
![image](https://user-images.githubusercontent.com/16497653/153206381-21cf6052-ee72-4121-b6d2-e06f38baa64c.png)

**Comment by cont1nuity** [comment]
This is not a Plater feature and most likely won't ever be.
Other addons, as the mentioned BigDebuffs or WeakAuras, do a way better job at tracking these and work in conjunction with Plater.
