### ISSUE TITLE
Feature request - NameplateHasAura with filter for casted by player

### ISSUE THREAD

**Issue by leewynn** [Tercioo/Plater-Nameplates#11]
Would be great if NameplateHasAura has additional parameter to filter by the specified player

**Comment by cont1nuity** [comment]
Actually discussing advanced aura caching for enhancements in #6 now.
This should lead to some possible improvements in this area.

**Comment by cont1nuity** [comment]
What would you need this for?
At current development, this will not be possible. It is available as "scriptEnv._Caster" for an idividual aura in a script, but not for mods at the moment. And Plater currently only caches auras which are shown.

**Comment by leewynn** [comment]
probably not needed, I think i misconfigured plater by adding those buffs to track and it's appearing for all instances
