### ISSUE TITLE
Dispellable buffs erroneously being hidden from nameplate

### ISSUE THREAD

**Issue by clicketz** [Tercioo/Plater-Nameplates#114]
**Game and Plater version**
![ver](https://user-images.githubusercontent.com/40314230/161477656-ba21fa5e-b340-4fff-846d-0c9880103a3e.png)

**Describe the bug**
Dispellable buffs are being removed from nameplates without actually being gone.

- Steps to Reproduce (what did you do to make the bug happen):

1. Turned off all addons other than Plater
2. Turned off all mods and scripts
3. Put more than 1 debuff on an NPC with a dispellable buff

- Result (what happens when you follow the steps above):

The dispellable buff disappears from the nameplate while still existing on the target

- Expected (what you think the expected behavior would be when following the steps):

The buff stays on the nameplate.

- When the bug started (a date, wow path release, details update, etc)?

When the UNIT_AURA change happened.

**Screenshots**
You can see here the buff is correctly showing on the nameplate (and on the target frame to the left)

![ver1](https://user-images.githubusercontent.com/40314230/161477666-469af36e-e977-4022-a517-7516c3555d15.png)

Next, we add a single debuff and everything is still working as expected.

![ver2](https://user-images.githubusercontent.com/40314230/161478122-8ed1f248-e953-4816-b7a7-85136d5b2afe.png)

Now, we add a second debuff and the dispellable buff disappears (I also add a third debuff, but it disappeared on the second debuff being added)

You can see on the target frame that the dispellable buff still existed on the target, just not on the nameplate.

![ver3](https://user-images.githubusercontent.com/40314230/161478269-17fc4085-9b1f-4d8e-a7c9-6f928f692195.png)

And here are my buff settings (NOTE: I tried with quite a few different settings checked and unchecked with no differing results.)

![ver4](https://user-images.githubusercontent.com/40314230/161478289-e31b7e83-f4aa-4e1f-89d4-82f9217c9b72.png)

**Comment by cont1nuity** [comment]
Working on it.
