### ISSUE TITLE
[Request] Upload to alternative addon providers

### ISSUE THREAD

**Issue by Daegalus** [Tercioo/Plater-Nameplates#115]
With the API changes to Curseforge, would it be possible for you to upload the addon to WoWInterface, WoWup, or wago? This way many third party addon managers can continue getting updates.

Or if not, permission for someone to upload them to an alternate site for you with appropriate disclaimers?

WoWUp doesnt even really need an upload, you just need to point it to this github: https://wowup.io/guide/wowup/hub

**Comment by cont1nuity** [comment]
CF, wago and GitHub releases are available. There is no intent in changing this.

**Comment by Daegalus** [comment]
is plater itself on wago? or just mods/scripts. Anyways, thanks for the answer, sorry to bother.

**Comment by cont1nuity** [comment]
It is available on wago addons and packaged on GitHub. If 3rd party updaters are not picking things up, that is on their end.
To my knowledge wowup does not handle WoWI through addon searches but just manual installations. Might be the same for wago and GitHub.

**Comment by Daegalus** [comment]
Yup, totally understand and my fault, I didn't look into it properly. My apologies.

**Comment by cont1nuity** [comment]
> Yup, totally understand and my fault, I didn't look into it properly. My apologies.

Nothing to worry about. :)
