### ISSUE TITLE
Problem with Havoc Debuff Trigger

### ISSUE THREAD

**Issue by flollef** [Tercioo/Plater-Nameplates#116]
***Game and Plater version**
Platerv349 Game 9.2.0

**Describe the bug**
When placed as a trigger under the "Buff and Debuffs" option for trigger type in the scripting module, the spell itself is not functioning as a trigger with either the 80240 or 335174 spell IDs. The code will not run when Havoc is cast.

**Lua Error**
None

**Comment by cont1nuity** [comment]
Works just fine on my end with the following: https://wago.io/wPPfK4uoi
Keep in mind: the debuff needs to show on the nameplate for scripts to trigger.

**Comment by flollef** [comment]
> Keep in mind: the debuff needs to show on the nameplate for scripts to trigger.

Ah! Fixed the issue.
