### ISSUE TITLE
Vertical Offset way smaller in combat that out of combat?

### ISSUE THREAD

**Issue by DoubleHighC** [Tercioo/Plater-Nameplates#117]
Hi there

Maybe I didn't recognise one or more settings, but I have the problem, that the space between the stacking nameplates vertically is nice when out of combat but get's reduced when in combat, so that the nameplates overlap vertically but just when I'm in combat!

Anyone any idea?

Thank you in advance

**Comment by cont1nuity** [comment]
Can this be reproduced with just Plater enabled?
Any screenshots?

**Comment by DoubleHighC** [comment]
Ohh sorry for sure you will not be able to locate the issue when there are a lot of addons beside Plater, didn't thought of that! But to be honest I will never ever disable all addons again! Did it twice and it was a desaster after enabling them again!

Sorry that I wasted your time and thank you for the answer! Thought maybe this is a common thing and I just missed a setting or so! Didn't want to dive deep into it! ;-)

**Comment by cont1nuity** [comment]
If you get a screenshot, it can probably be narrowed down.
