### ISSUE TITLE
[Feature Request] Add option for fixed border size for buffs

### ISSUE THREAD

**Issue by Mistrick** [Tercioo/Plater-Nameplates#118]
Would be nice add option for fixed border size. Little move and it looks weird sometimes(one side with 2px border and 3 others with 1px border).
Add separate option for each buff frame (aura frame 1, aura frame 2 and special buffs)
![image](https://user-images.githubusercontent.com/4307674/168337215-0ea1e15f-c68b-486f-bcd7-b684dc4cd64e.png)
![image](https://user-images.githubusercontent.com/4307674/168337282-995a409e-1958-451f-98b6-24ea3b65a468.png)

**Comment by cont1nuity** [comment]
This has been added in the meantime.
