### ISSUE TITLE
Option to allow dispellable debuffs over 2 minutes

### ISSUE THREAD

**Issue by Elfarion** [Tercioo/Plater-Nameplates#124]
In Plater build "Plater-v352", Dispellable buffs won't show if its duration is bigger than 2 minutes.

I liked this feature to see Power word fortitude, earth shield etc. for purging.

Would you consider making an option, that allow them to be shown if you tick a checkbox?

I have currently modfied the lua file myself in the addon to bring it back, but would be nice if I didn't have to make custom changes to the code.

**Comment by cont1nuity** [comment]
The option is already implemented in the alpha versions and will be part of the next release.
