### ISSUE TITLE
[Feature Request] Add option for Hide welcome masseges 

### ISSUE THREAD

**Issue by gaveer** [Tercioo/Plater-Nameplates#126]
Can we add option to hide welcome massege when logging to the game
![Screenshot_6](https://user-images.githubusercontent.com/45834601/187083948-4b6ee6ee-d6f1-49f1-af6b-781e98001096.png)

![Screenshot_7](https://user-images.githubusercontent.com/45834601/187083974-7fa7b44f-3aae-4b0e-85e6-8e5ef72896bf.png)

**Comment by cont1nuity** [comment]
It is printed when using the `/plater` chat command, not on login.
I'll think about moving it to "help" or "?".

**Comment by gaveer** [comment]
nice
