### ISSUE TITLE
Clamping/Adibags Lua Errors

### ISSUE THREAD

**Issue by Ophilla** [Tercioo/Plater-Nameplates#129]
**Game and Plater version**
WoW Version: 9.2.7.45338
Plater version info: Plater-v534-Retail - DF v335 - 9.2.7

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
Truthfully, I have no idea what causes this to happen. It seems random. It doesn't even happen every time I play wow, and I'm not sure it happens on every character, although I use Plater and Adibags on pretty much all of my characters. Sometimes it happens in the middle of combat and I get a message in the chat telling me the lua error will open when I exit combat. When I do get them, they come very frequently, maybe every few seconds. I could be wrong, but I do NOT seem to remember it happening while inside instances.

- Result (what happens when you follow the steps above):
Nothing actually looks wrong, I just get constant error messages, frequently mentioning Adibags and/or clamping.

- Expected (what you think the expected behavior would be when following the steps):

- When the bug started (a date, wow path release, details update, etc)?
It's been going on for at least a few weeks, I think. Since nothing seems to actually be wrong and I'm usually busy doing something, I'm in the habit of just clicking it away.

- Additional information:

**Lua Error**
There have been several, maybe 5 or 6 that vary just slightly. I had 4 other ones earlier, but it seems they (at least sometimes) go away after a reload, so this older one from BugSack is all I have at the moment. 

4x [ADDON_ACTION_BLOCKED] AddOn 'Plater' tried to call the protected function 'SetTargetClampingInsets()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetTargetClampingInsets'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:336: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:275>
[string "=[C]"]: in function `SetupClassNameplateBars'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:119: in function `OnNamePlateAdded'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:47>

**Screenshots**

**Other Information**

**Comment by cont1nuity** [comment]
Looks like a pretty common taint error that could be caused by everything.
Please do the following:
- enable taintlog: `/console taintlog 1`
- restart the game
- let the error happen again
- exit the game and send over the `WoW\_retail_\logs\taint.log`
- (start the game again and disable taintlog again `/console taintlog 0`)
That log usually gives a good indication for the culprit.
Ensure that all your addons are up to date as well.

**Comment by Ophilla** [comment]
Well, this is definitely.. Different. Now that I'm looking at this, I'm only about 70% sure that the error during the log was the same Plater error. I've certainly encountered a lot of errors when using Scrap and Guild Roster Manager together that didn't look at all related to my Plater problem. I'll try again, and in the meantime try to contact the Scrap author.

[scrap taint.log](https://github.com/Tercioo/Plater-Nameplates/files/9592954/scrap.taint.log)

**Comment by cont1nuity** [comment]
It would help if you provided the full log for reference.

**Comment by Ophilla** [comment]
I'm sorry? That's the whole file that was in the location you mentioned. Do you mean a different log?

**Comment by cont1nuity** [comment]
In that case the error mentioned initially did not occur yet. The `taint.log` should contain the full error.

**Comment by Ophilla** [comment]
Oh! I'm sorry, I just remembered because I stumbled across it again; I copied the error before I closed the game because it didn't get caught by buggrabber (and it usually doesn't, which is why I only had the slightly different error before). This looks much more like the usual error I would get, as opposed to the one in the original post. I really thought I closed the game immediately, but that would put the taint log about 2 hours in the future.

Message: ADDON_ACTION_BLOCKED: Plater tried to call the protected function 'SetTargetClampingInsets()'.
Time: Sat Sep 17 20:34:20 2022
Count: 5
Stack: ADDON_ACTION_BLOCKED: Plater tried to call the protected function 'SetTargetClampingInsets()'.
[string "@Interface\AddOns\Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...rap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Scrap\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...face\AddOns\Scrap\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `SetTargetClampingInsets'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:336: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:275>
[string "=[C]"]: in function `SetupClassNameplateBars'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:119: in function `OnNamePlateAdded'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals: <none>

**Comment by Ophilla** [comment]
I will keep logging and waiting for it to happen again, but I don't know how to trigger it.

**Comment by Ophilla** [comment]
I was able to catch it. Here's the [taint.log](https://github.com/Tercioo/Plater-Nameplates/files/9681698/taint.log).

**Comment by cont1nuity** [comment]
Did you turn on taintlog after the error occurred?

**Comment by cont1nuity** [comment]
Known addons to cause taints, currently: Clique and TotalRP3

**Comment by Ophilla** [comment]
I caught it again and I'm afraid it looks exactly the same, but I'll upload it in case you see something I don't. [[taint.log]](https://github.com/Tercioo/Plater-Nameplates/files/9791214/taint.log)

I don't use Clique or TotalRP3, so I guess this one must be something else. My addon list is long enough to make anyone cringe, so without knowing how to trigger the error, I really hesitate to do any sort of trial of elimination. I'll try the other console command and see if it gives anything different.

**Comment by cont1nuity** [comment]
Running log level 11 might help then. Nothing to see there...

**Comment by Ophilla** [comment]
This is the second time it has popped up in Ember Court, which I've started doing recently. The log is quite long I guess, too big to upload here (52 MB). I tried to upload it to pastebin but it locks the site up. :I Is there another way I can get it to you?

**Comment by cont1nuity** [comment]
Zip it and upload should work just fine.

**Comment by Ophilla** [comment]
Ah, okay, perfect. [[taint.zip]](https://github.com/Tercioo/Plater-Nameplates/files/9835317/taint.zip)

**Comment by cont1nuity** [comment]
Some candidates:
- BattlePetBreedID
- BetterAddonList
- MobInfo2
- XLoot_Master
- AdiBags
- CanIMogIt
- Maybe some older Versions of WQT or some other addons

Might be worth investigating those.

**Comment by Ophilla** [comment]
Great! Thank you so much for your patience and effort to help me figure this out.
