### ISSUE TITLE
Not seeing execute range on hunter kill shot

### ISSUE THREAD

**Issue by trey-k** [Tercioo/Plater-Nameplates#130]
**Game and Plater version**
Plater-v535-Wrath - DF v367 - 3.4.0

**Describe the bug**
Not seeing Kill Shot execute range for hunters on plates, execute box in general settings indicators is checked and still able to see it on paladin

**Comment by cont1nuity** [comment]
Try the latest alpha version. It should be added there.

**Comment by cont1nuity** [comment]
No further response. v356.1 contains the change.
