### ISSUE TITLE
Quest NPCs are not colored (orange)

### ISSUE THREAD

**Issue by Emoosch** [Tercioo/Plater-Nameplates#131]
WotLK 3.4.0 / Plater v536 (todays Update 09.10.2022)

The quest NPCs are no more colored in orange.

https://paste.pics/J2FWN

**Comment by Tercioo** [comment]
tested just now:   you sure the option is enabled?

------ Original Message ------
From: "Emoosch" ***@***.***>
To: "Tercioo/Plater-Nameplates" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: 09-Oct-22 6:31:16 PM
Subject: [Tercioo/Plater-Nameplates] Quest NPCs are not colored (orange) 
(Issue #131)

**Comment by cont1nuity** [comment]
Works perfectly fine on my end. I'd argue some mod is changing/resetting the color again.

**Comment by Emoosch** [comment]
The latest update yesterday (536.1) fixed it i guess, its working now again. :)
