### ISSUE TITLE
Wrong self count in the function Plater.IsQuestObjective

### ISSUE THREAD

**Issue by juntereiner** [Tercioo/Plater-Nameplates#132]
**Game and Plater version**
Retail and last version.

**Describe the bug**

I use this plugin to show quest objectives numbers in nameplates: https://wago.io/PMdq2Rg_N . It uses the function Plater.IsQuestObjective which parse every lines of the tooltip to find numbers. Except it is always the number of the last member of the group, not yours. So it works when you are solo, but not in a group.

In plater.lua, around 9330, the line `questData.amount = amount1` should be inside the condition `if yourQuest ~= false then` for this to work.

**Comment by cont1nuity** [comment]
The proposed change would fully remove quest completion data from other players, which is not intended.
I will have a look at it though, as tracking individual or necessary group progress should be a thing.
`questData.ownAmount` will be a thing in addition to the existing values.

**Comment by juntereiner** [comment]
It works great, thank you.
