### ISSUE TITLE
Firestarter

### ISSUE THREAD

**Issue by Effeh** [Tercioo/Plater-Nameplates#139]
sorry, I have no idea how to use github properly, but I noticed firestarter upper execute wasn't working:

```LUA
				elseif (class == "MAGE") then
					if IsPlayerSpell(269644) then -- Searing Touch
						lowExecute = 0.3
					elseif IsPlayerSpell(205026) then --Firestarter
						highExecute = 0.9
					end
```

think should be

```LUA
				elseif (class == "MAGE") then
					if IsPlayerSpell(269644) then -- Searing Touch
						lowExecute = 0.3
					end	
					if IsPlayerSpell(205026) and upperEnabled then --Firestarter
						highExecute = 0.9
					end
```

just modelled it after the hunter codeblock. Actually now that I look at hunter again, careful aim/killer instinct are dependent on knowing kill shot, and it's theoretically possible to at least have killer instinct without kill shot:

```LUA
				elseif (class == "HUNTER") then
					if IsPlayerSpell(53351) then -- Kill Shot
						lowExecute = 0.2
					end
					if IsPlayerSpell(273887) then --> is using killer instinct?
						lowExecute = 0.35
					end
					if IsPlayerSpell(260228) and upperEnabled then --> Careful Aim
						highExecute = 0.7
					end
```

**Comment by cont1nuity** [comment]
Thank you for the report. This is due to changes in the talent/spell APIs with the new talent trees.

Please use the template next time.
