### ISSUE TITLE
`C_ClassTalents.GetActiveConfigID()` returns nil for new characters

### ISSUE THREAD

**Issue by KOVIKO** [Tercioo/Plater-Nameplates#144]
There's a function `isTalentLearned` that starts on line 1203 on Plater.lua (in the latest alpha build via CurseForge) that causes a bug when attempting to use `C_Traits.GetNodeInfo` with a nil config ID. This can be nil on a brand new character (and maybe more than that, I'm not sure), causing an error.

A quick & dirty patch is to break `isTalentLearned` prematurely with `false` if `C_ClassTalents.GetActiveConfigID()` is nil.

**Comment by cont1nuity** [comment]
Thank you. Fixed with b07661e
