### ISSUE TITLE
Quest Icon not showing 

### ISSUE THREAD

**Issue by Yukio83** [Tercioo/Plater-Nameplates#145]
**Game and Plater version**
Which is the game version and Plater version you're using?
Plater-v539-Retail - DF v398 - 10.0.2

The Quest Icon is not showing next to mobs needed to complete a quest. The option is active in General Settings.
Nameplate still change color as expected.

Thank you

**Comment by cont1nuity** [comment]
This indicator is, as the tooltip suggest, for quest bosses only. Those are identified via wow game APIs.
For regular quest progress / icons, get a mod from wago.io
