### ISSUE TITLE
Spam / Lag Causes by an String error!

### ISSUE THREAD

**Issue by iCry1337** [Tercioo/Plater-Nameplates#149]
![https://i.imgur.com/CZ1vYxW.png](https://i.imgur.com/CZ1vYxW.png)

Spam / Lag Causes by an String error!

**Comment by cont1nuity** [comment]
Please test the latest alpha version. Should be fixed there.

**Comment by iCry1337** [comment]
ill give it a try, thank you

**Comment by cont1nuity** [comment]
Resolved with fixes of the corresponding scripts.
