### ISSUE TITLE
Not a bug but request

### ISSUE THREAD

**Issue by DiscipleDarkfriend** [Tercioo/Plater-Nameplates#150]
Wanted to request Plater cover Critters/Battle pets, as someone who always has one out it is most jarring to have vanilla plates on them.

**Comment by cont1nuity** [comment]
If you are referring to the units in Valdrakken: those are beasts, not critters but beasts.
Plater behavior won't change for those, as they work as expected.
You can use a "Hide by unitID" script from wago to hide them if you like.
Battlepets follow friendly npc rules and can be hidden via mods as well if so desired.

**Comment by cont1nuity** [comment]
No further answer/comment since two weeks.
