### ISSUE TITLE
Importing Scripts not visible after reloading UI

### ISSUE THREAD

**Issue by holyprin** [Tercioo/Plater-Nameplates#151]
Title kind of says it. When I import custom scripts they don't seem to be editable after a reload/logout, they are completely missing from the list on the left side...

**Comment by cont1nuity** [comment]
Please provide some screenshots and ensure that other profile changes (whichever) persist.

**Comment by holyprin** [comment]
All you're going to see in screenshots are the scripts there one minute and gone after a reload. Beyond that I uninstalled it and went with something else for now.

**Comment by cont1nuity** [comment]
What about other setting changes? Do those persist?
you might want to verify that all your files in the WTF folder are writable and not set to read-only.
