### ISSUE TITLE
[Feature request] Enable cosmetic user changes to persist through updates (of profiles)

### ISSUE THREAD

**Issue by Belatar** [Tercioo/Plater-Nameplates#153]
**Game and Plater version**
Which is the game version and Plater version you're using?
Plater-v547-18-gb93ccb1-Retail - DF v411 - 10.0.2

**Other Information**
i imported a plater profile via the weakauras companion. i changed only font type and sizes to the one that match the rest of my ui. it seems there is no way to keep those cosmetic changes during an update (at least i didnt find it and in discord there was no response to my question) and its a quite tedious process.
is it possible to change config in a way that user changes persist through updates (unless the parameter becomes obsolete or breaks functionality)? would be really great.

**Comment by cont1nuity** [comment]
The only things that won't be changed during a profile update are mods/script that you added yourself and mod/script options. It will stay this way.
