### ISSUE TITLE
Anchor point resetting

### ISSUE THREAD

**Issue by Cassul** [Tercioo/Plater-Nameplates#155]
Hi

 

In the advanced section there's an option to select the anchor point for the health bars, I tend to go for head/feet option but everytime I reload, relog it resets it back to head as the anchor point.

WoW DF 10.0.2.47631
Date 01.21.2023

UPD: can it be fixed?

**Comment by cont1nuity** [comment]
What does `/plater cvar nameplateOtherAtBase` print in chat?

**Comment by Cassul** [comment]
> What does `/plater cvar nameplateOtherAtBase` print in chat?

name: 'nameplateOtherAtBase'
Current Value: 1
Stored Value: 1
Last changed by:
Interface/Addon/Plater/Plater_OptionsPanel.lua:1331

**Comment by cont1nuity** [comment]
And after login / when it is reset?

**Comment by Cassul** [comment]
> And after login / when it is reset?

name: 'nameplateOtherAtBase'
Current Value: 0
Stored Value: 1
Last changed by:
Interface/Addon/Plater/Plater_OptionsPanel.lua:1331

after login\reload\afk ...

**Comment by cont1nuity** [comment]
So, as the stored value is OK, I assume some other addon is changing it.
Try disabling all other addons and see if the issue persists.

**Comment by Cassul** [comment]
> So, as the stored value is OK, I assume some other addon is changing it. Try disabling all other addons and see if the issue persists.

thx  for this advice
This makes AFK mode ElvUI. This is strange because the health indicators in ElvUI are disabled.
Disabled AFK in ElvUI. I'll watch further ...

**Comment by cont1nuity** [comment]
Ok, thanks for letting me know.
