### ISSUE TITLE
Targets not selectable when clicking on aura on nameplate

### ISSUE THREAD

**Issue by tonysathre** [Tercioo/Plater-Nameplates#156]
**Game and Plater version**
Which is the game version and Plater version you're using?
Full `/plater version` output please.
v549-Retail - DF v413 - 10.0.5

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
  1. Cast any spell that places an aura on the target A's nameplate
  2. Select target B
  3. Try to re-target, target A by clicking on the aura on it's nameplate
 
- Result (what happens when you follow the steps above):
  * Target is not selected
- Expected (what you think the expected behavior would be when following the steps):
  * Target should be targetted
- When the bug started (a date, wow path release, details update, etc)?
As far as I know, it's always been this way.
- Additional information:
I'm not sure this actually a bug or intentional, but it would be nice to have a toggle in the settings that would make it possible to select a target by clicking on auras on the nameplate for classes like affliction warlock.

I also tried changing the height of the `Enemy Box Selection Space` setting but even if that was increased to encompass the entire size of the aura, it was still not selectable.

**Lua Error**
Post here lua errors, if you aren't getting any, use */console scriptErrors 1*

**Screenshots**
Post images of the bug if necessary.

**Other Information**
If necessary, add more info here.

**Comment by cont1nuity** [comment]
This is usually due to aura tooltips being enabled on the buff settings tab. Try disabling them.

**Comment by tonysathre** [comment]
> 

That was it. Thank you.
