### ISSUE TITLE
Debuff icons are not shown on adds of Overgrown Ancient

### ISSUE THREAD

**Issue by icekylinH** [Tercioo/Plater-Nameplates#158]
**Game and Plater version**
Plater-v552-Retail -DEF v415 -10.0.5

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
- cast dot on Overgrown Ancient

- Result (what happens when you follow the steps above):
- debuff icon doesn't display

- Expected (what you think the expected behavior would be when following the steps):
- it should display

- When the bug started (a date, wow path release, details update, etc)?
- start from 548, v547 was normal

- Additional information:

**Lua Error**
Post here lua errors, if you aren't getting any, use */console scriptErrors 1*

**Screenshots**
Post images of the bug if necessary.

**Other Information**
If necessary, add more info here.

**Comment by cont1nuity** [comment]
Those adds are considered "performance units" and won't update threat/auras.
You can turn that off with a new mod by adding the following to the "Initialization" hook:
`Plater.RemovePerformanceUnits(196642)`
