### ISSUE TITLE
Error Message about CastBar in Game after/during combat

### ISSUE THREAD

**Issue by stamicvs** [Tercioo/Plater-Nameplates#160]
**Game and Plater version**
Plater-v554.1-1-gbacf1e6-Retail - DF v420 - 10.0.5

**Describe the bug**
Error Message occurs in BugSack after/during combat

**Lua Error**
BugSack output:
4x Plater/Plater.lua:6246: attempt to index field 'CastBar' (a nil value)
[string "@Plater/Plater.lua"]:6246: in function `UpdateBaseNameplateOptions'
[string "@Plater/Plater.lua"]:4936: in function <Plater/Plater.lua:4933>
[string "=[C]"]: in function `UpdateNamePlateOptions'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:95: in function <...eBlizzard_NamePlates/Blizzard_NamePlates.lua:69>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetCVar'
[string "@SharedXML/CvarUtil.lua"]:13: in function <SharedXML/CvarUtil.lua:9>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetCVar'
[string "@Plater/Plater.lua"]:2198: in function <Plater/Plater.lua:2179>

Locals:
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = NamePlate1 {
 }
}
(for control) = 1
_ = 1
plateFrame = NamePlate1 {
 TargetNeonUp = Texture {
 }
 Plater = true
 isNamePlate = true
 PlayBodyFlash = <function> defined @Plater/Plater.lua:8973
 ApplyOffsets = <function> defined @Blizzard_NamePlates/Blizzard_NamePlates.lua:539
 HasUpdateScheduled = <userdata>
 playerHasAggro = false
 IsFriendlyPlayerWithoutHealthBar = false
 unitName = FontString {
 }
 SpellAnimations = <table> {
 }
 QuestInfo = <table> {
 }
 namePlateUnitNameLower = "priodia"
 RaidTarget = Texture {
 }
 isSoftInteract = false
 template = "NamePlateUnitFrameTemplate"
 FocusIndicator = Texture {
 }
 IconIndicators = <table> {
 }
 unitFramePlater = NamePlate1PlaterUnitFrame {
 }
 Top3DFrame = NamePlate13DFrame {
 }
 IsSelf = true
 OnTickFrame = Frame {
 }
 driverFrame = NamePlateDriverFrame {
 }
 OnRemoved = <function> defined @Blizzard_NamePlates/Blizzard_NamePlates.lua:526
 OnAdded = <function> defined @Blizzard_NamePlates/Blizzard_NamePlates.lua:515
 ActorNameSpecial = FontString {
 }
 OnOptionsUpdated = <function> defined @Blizzard_NamePlates/Blizzard_NamePlates.lua:533
 debugAreaTexture = Texture {
 }
 ActorTitleSpecial = FontString {
 }
 unitFrame = NamePlate1PlaterUnitFrame {
 }
 actorType = "player"
 namePlateUnitReaction = 5
 IsNpcWithoutHealthBar = false
 namePlateClassification = "normal"
 CurrentUnitNameString = FontString {
 }
 0 = <userdata>
 GetAdditionalInsetPadding = <function> defined @Blizzard_NamePlates/Blizzard_NamePlates.lua:557
 isSelf = true
 th_threat = Frame {
 }
 isPlayer = true
 namePlateUnitGUID = "Player-570-0A959F73"
 namePlateIsQuestObjective = false
 namePlateUnitToken = "nameplate1"
 UnitFrame = Button {
 }
 debugAreaText = FontString {
 }
 Obscured = Texture {
 }
 isBattlePet = false
 TargetNeonDown = Texture {
 }
 PlateConfig = <table> {
 }
 NameAnchor = 0
 namePlateUnitName = "Priodia"
 OnSizeChanged = <function> defined @Blizzard_NamePlates/Blizzard_NamePlates.lua:587
 isWidgetOnlyMode = false
 GetPreferredInsets = <function> defined @Blizzard_NamePlates/Blizzard_NamePlates.lua:568
}
(*temporary) = <function> defined @FrameXML/RestrictedInfrastructure.lua:124
(*temporary) = nil
(*temporary) = "showCastbar"
(*temporary) = "attempt to index field 'CastBar' (a nil value)"
Plater = <table> {
 ExportScriptToGroup = <function> defined @Plater/Plater.lua:13035
 ActorTypeSettingsCache = <table> {
 }
 ImportScriptsFromLibrary = <function> defined @Plater/Plater.lua:12535
 SetNameplateColor = <function> defined @Plater/Plater.lua:10634
 ScriptAura = <table> {
 }
 IconPick = <function> defined @Details/Libs/DF/panel.lua:1480
 RestoreCVar = <function> defined @Plater/Plater.lua:10147
 SetCastBarSize = <function> defined @Plater/Plater.lua:10668
 UpdatePersonalBar = <function> defined @Plater/Plater.lua:4764
 databroker = <table> {
 }
 GetSpecIconForUnitFromBG = <function> defined @Plater/Plater.lua:10055
 ScheduleTimer = <function> defined @DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:94
 DebugTargetNameplate = <function> defined @Plater/Plater_DebugFrames.lua:11
 RegisterScriptComm = <function> defined @Details/Libs/DF/fw.lua:4960
 ShowPanicWarning = <function> defined @Details/Libs/DF/panel.lua:1825
 db = <table> {
 }
 SetEnabledState = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 FindAndSetNameplateColor = <function> defined @Plater/Plater.lua:5863
 OnHealthChange = <function> defined @Plater/Plater.lua:5668
 AddCompanionData = <function> defined @Plater/Plater_ScriptingPanels.lua:482
 UpdateSelfPlate = <function> defined @Plater/Plater.lua:6002
 SetCastBarC

**Comment by cont1nuity** [comment]
Should be fixed with the latest alpha version.
