### ISSUE TITLE
showEnemyTotems switches to enabled on loading screen to arena

### ISSUE THREAD

**Issue by RevinderDev** [Tercioo/Plater-Nameplates#164]
**Game and Plater version**
Which is the game version and Plater version you're using?
Full `/plater version` output please.
![image](https://user-images.githubusercontent.com/32570664/231006886-c88829ab-2436-4629-ac5a-6ff5daba7bfb.png)

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
1. Disable `Show Enemy Totems`.
2. Go to the arena,
- Result (what happens when you follow the steps above):
Show Enemy totems is enabled,
- Expected (what you think the expected behavior would be when following the steps):
Show Enemy Totems is disabled.
- When the bug started (a date, wow path release, details update, etc)?
Today
- Additional information:
I have no idea why, but I am losing my mind over this. Every time I join arena, it is enabled. I tried checking to see if this is because of interface option. I tried checking if it is like that in SavedVariables, and it looks like so:
```
	["saved_cvars"] = {
				["nameplateOverlapV"] = "0.78999996185303",
				["nameplateShowEnemyMinus"] = "0",
				["nameplateMaxDistance"] = "41",
				["nameplateShowEnemyGuardians"] = "1",
				["nameplateShowEnemyMinions"] = "0",
				["nameplateShowFriendlyPets"] = "1",
				["nameplateShowFriendlyNPCs"] = "0",
				["nameplateShowEnemyPets"] = "1",
				["nameplateShowEnemies"] = "1",
				["nameplateShowEnemyTotems"] = "0",
				["nameplateMotion"] = "1",
			},
```

**Lua Error**
There is no error.
**Screenshots**
Post images of the bug if necessary.
N/A

**Other Information**
If necessary, add more info here.

**Comment by cont1nuity** [comment]
Please check the "Auto" tab in the Plater settings.

**Comment by RevinderDev** [comment]
I have everything in there disabled.
![image](https://user-images.githubusercontent.com/32570664/231015691-25e86baf-2b12-4d38-81b3-5f07b721fd6e.png)

**Comment by cont1nuity** [comment]
In that case please verify that this happens with all other addons disabled.

**Comment by RevinderDev** [comment]
Disabled every addon and it seems to have worked.

Narrowed it down by enabling/disabling to [Gladdy](https://www.curseforge.com/wow/addons/gladdy-classic).

I don't quite understand why would Gladdy influence private Plater variable. What can I do about it? There is no good replacement for what Gladdy does for me.

**Comment by cont1nuity** [comment]
This is not a Gladdy or Plater setting, but a blizzard CVar. Every addon is free to change that.
I am pretty sure there are options in Gladdy to change that behavior.

**Comment by RevinderDev** [comment]
Apologies for submitting unnecessary issue then and thank you for helping out <3

For anyone finding it afterwards do this in Gladdy:
![image](https://user-images.githubusercontent.com/32570664/231216045-5f874d43-2c1b-4989-9bc1-2554bddfa73e.png)

This will hide `Plater` nameplates even though they are enabled in `Advanced` tab, thus showing only totem pulses.

 As a sidenote, I would be more than happy to ditch that module from Gladdy to have something like that in `Plater` but I could not find how to do it.

**Comment by cont1nuity** [comment]
Always here to help.
If you open an enhancement request or join the discord, we can discuss additional features.
Some functionality is easily modded and might exist in one form or another on wago.io already.
