### ISSUE TITLE
[Feature request] Plater names & bars behind dialog bubbles

### ISSUE THREAD

**Issue by antarek** [Tercioo/Plater-Nameplates#166]
Version:
v557.1 retail DF v423 10.1.0

Description:
For the moment i haven't been able to display dialog bubbles over Plater names and bars. Having a way to have dialog bubles displayed over Plater names and bars would hel when trying to read them.

Screenshot:
![image](https://user-images.githubusercontent.com/42368527/236645554-bee2555e-b7c6-4dfd-95eb-c7d9fc57e14a.png)

**Comment by cont1nuity** [comment]
As addons cannot alter chat bubbles in dungeons or raids and as they are on a DIALOG layer, that's pretty much impossible.
Setting nameplate strata to dialog on the level and strata tab might yield some results.
For open world there might be addons which alter the chat bubbles and might be able to change them to a lower layer, but that's about it.
For plater: nothing to be implemented as the game limitations are against it.
