### ISSUE TITLE
Plater colors for horde and ally

### ISSUE THREAD

**Issue by mrlinuxdude** [Tercioo/Plater-Nameplates#169]
How can i change my colors for horde text name.  I was able to do it with ally on my main toon but when i go to horde there are no colors. I have looked in the FAQs and could find how to set the colors for horde when i switch toons not working

**Comment by cont1nuity** [comment]
I don't quite understand the issue. Some screenshots would probably help.

**Comment by mrlinuxdude** [comment]
Like when you see the characters,toons name. color for that. ally and horde when i change color on ally side then go on my horde toon the color is not there shows white text.  There should be easier way for colors change bothsides races

**Comment by cont1nuity** [comment]
I am still not 100% sure about what you mean, please include a screenshot.

**Comment by mrlinuxdude** [comment]
There should be easier way for colors change bothsides races?

**Comment by cont1nuity** [comment]
If you don't include requested screenshots you can consider this issue closed.

**Comment by mrlinuxdude** [comment]
i will get back to you with the screenshots

**Comment by mrlinuxdude** [comment]
![platerhelpsl](https://github.com/Tercioo/Plater-Nameplates/assets/109782016/a3e9547c-85e2-4a63-a92e-a189b044ca07)

OK here is the screenshot. As you can see I have alliance as blue. and Horde is on the right with no color name. I want to make it red. So its alliance blue Horde red.

**Comment by cont1nuity** [comment]
Can't be done. Blizzard does not provide nameplates for enemy faction in sanctuaries.
The other way around is the same: if you're horde, the opposing players won't get nameplates and always display the small default blizzard names.

**Comment by mrlinuxdude** [comment]
OK
