### ISSUE TITLE
Afflicted Mobs are not shown in Plater 

### ISSUE THREAD

**Issue by Angas96** [Tercioo/Plater-Nameplates#171]

**Comment by cont1nuity** [comment]
This is not an issue of Plater.
Blizzard enforces default nameplates for friendly units in dungeons and raids, so ensure that all blizzard options (CVars) are setup to show friendly NPCs at all times. e.g.:
- always show nameplates
- disable "hide blizzard healthbars"
- enable friendly NPCs
- enable friendly nameplates
- set blizzard name options to show all NPCS
