### ISSUE TITLE
How to uniformly opt out transparency altogether for nameplates in every possible state?

### ISSUE THREAD

**Issue by nakhodkin** [Tercioo/Plater-Nameplates#172]
My goal is to disable transparency for enemy nameplates that are not my target regardless they are in/out of range, in/out of combat, so basically all enemy nameplates would not have any opacity applied to it.

I'm pretty sure that this is achievable through any combination of available controls, unfortunately I was unable to locate the exact configuration options for this.

<img width="1792" alt="Screenshot 2023-06-09 at 19 55 57" src="https://github.com/Tercioo/Plater-Nameplates/assets/14351638/31340a00-fbf8-45a2-958f-54f2e69067c7">

I'm using the following version of the addon v560.4

**Comment by cont1nuity** [comment]
I'd argue you have some alpha mod active on your modding tab. Check there. Or try a default profile first.
