### ISSUE TITLE
Classic Era PTR: Attempt to call method 'SetGradientAlpha' (a nil value)

### ISSUE THREAD

**Issue by kriminy** [Tercioo/Plater-Nameplates#175]
For Classic Era Hardcore PTR (toc 1.14.4) with Plater version v560.4-22-gb4b772d-Classic - DF v444 - 1.14.4
I'm getting the following Lua error when logging in. In addition, most of the functionality of the add-on seems to be broken at the moment.

2x Plater/libs/DF/picture.lua:335: attempt to call method 'SetGradientAlpha' (a nil value)
[string "@Plater/libs/DF/picture.lua"]:335: in function <Plater/libs/DF/picture.lua:269>
[string "=(tail call)"]: ?
[string "@Plater/libs/DF/cooltip.lua"]:255: in function `createTooltipFrames'
[string "@Plater/libs/DF/cooltip.lua"]:330: in function `CreateCoolTip'
[string "@Plater/libs/DF/cooltip.lua"]:3651: in main chunk

Locals:
self = <table> {
 DropDownCounter = 747047
 CreateFrameContainer = <function> defined @Plater/libs/DF/containers.lua:487
 IsUnitTapDenied = <function> defined @Plater/libs/DF/fw.lua:5128
 NewLabel = <function> defined @Plater/libs/DF/label.lua:255
 SavedVars = <table> {
 }
 AdjustmentSliderOptions = <table> {
 }
 PanelCounter = 747047
 MakeFunctionSecure = <function> defined @Plater/libs/DF/fw.lua:5372
 debug = false
 LabelNameCounter = 747047
 DefaultMetaFunctionsSet = <table> {
 }
 GetCurrentSpec = <function> defined @Plater/libs/DF/fw.lua:4353
 alias_text_colors = <table> {
 }
 ScriptHookMixin = <table> {
 }
 BackdropUtil = <table> {
 }
 RegisterScriptComm = <function> defined @Plater/libs/DF/fw.lua:5070
 UnitGroupRolesAssigned = <function> defined @Plater/libs/DF/fw.lua:232
 ShowTutorialAlertFrame = <function> defined @Plater/libs/DF/fw.lua:2786
 CooldownsExternals = <table> {
 }
 GetSpecializationRole = <function> defined @Plater/libs/DF/fw.lua:291
 SpecListByClass = <table> {
 }
 FRAMELEVEL_BACKGROUND = 150
 GetDefaultColorList = <function> defined @Plater/libs/DF/colors.lua:176
 button_templates = <table> {
 }
 HeaderMixin = <table> {
 }
 FrameMixin = <table> {
 }
 SplitTextInLines = <function> defined @Plater/libs/DF/fw.lua:658
 CreateSwitch = <function> defined @Plater/libs/DF/slider.lua:872
 font_templates = <table> {
 }
 embeds = <table> {
 }
 SetAnchor = <function> defined @Plater/libs/DF/fw.lua:1445
 GetDefaultBackdropColor = <function> defined @Plater/libs/DF/fw.lua:65
 trim = <function> defined @Plater/libs/DF/fw.lua:1095
 NewSplitBar = <function> defined @Plater/libs/DF/split_bar.lua:716
 LayeredRegionMetaFunctionsSet = <table> {
 }
 FindClassForCooldown = <function> defined @Plater/libs/DF/spells.lua:1269
 ChartFrameMixin = <table> {
 }
 TooltipHandlerMixin = <table> {
 }
 DebugVisibility = <function> defined @Plater/libs/DF/fw.lua:5382
 MakeStringFromSpellId = <function> defined @Plater/libs/DF/fw.lua:974
 BarNameCounter = 747047
 CreateTexture = <function> defined @Plater/libs/DF/picture.lua:251
 SetFontShadow = <function> defined @Plater/libs/DF/fw.lua:904
 CreateOptionsFrame = <function> defined @Plater/libs/DF/fw.lua:2876
 SetEnvironment = <function> defined @Plater/libs/DF/fw.lua:5364
 Dispatch = <function> defined @Plater/libs/DF/fw.lua:4412
 CoreDispatch = <function> defined @Plater/libs/DF/fw.lua:4437
 MapRangeUnclamped = <function> defined @Plater/libs/DF/math.lua:46
 GetBestFontPathForLanguage = <function> defined @Plater/libs/DF/fw.lua:3028
 SortFunctions = <table> {
 }
 www_icons = <table> {
 }
 NewButton = <function> defined @Plater/libs/DF/button.lua:907
 PotionIDs = <table> {
 }
 CreatePool = <function> defined @Plater/libs/DF/fw.lua:5236
 AddClassIconToText = <function> defined @Plater/libs/DF/fw.lua:997
 GetBezierPoint = <function> defined @Plater/libs/DF/math.lua:72
 PayloadMixin = <table> {
 }
 ClassSpecIds = <table> {
 }
 DefaultSecureScriptEnvironmentHandle = <table> {
 }
 RemoveRealName = <function> defined @Plater/libs/DF/fw.lua:860
 GetClassTCoordsAndTexture = <function> defined @Plater/libs/DF/fw.lua:985
 FormatColor = <function> defined @Plater/libs/DF/fw.lua:1493
 SwitchCounter = 747047
 AddMemberForWidget = <function> defined @Plater/libs/DF/fw.lua:3269
 InstallTemplate = <function> defined @Plater/libs/DF/fw.lua:3172
 HeaderFunctions = <table> {
 }
 FlaskIDs = <table> {
 }
 GetFontSize = <function> defined @Plater/libs/DF/fw.lua:1039
 IsShadowlandsWow = <fu

![image](https://github.com/Tercioo/Plater-Nameplates/assets/16073728/17a23bf5-c48a-48b9-a01f-dacde65f2567)

**Comment by Tercioo** [comment]
![image](https://github.com/Tercioo/Plater-Nameplates/assets/9000280/bb3d4c3f-cf54-4b58-a98b-7a20a942d937)
Is the wow classic era PTR?

**Comment by cont1nuity** [comment]
There has been no work done towards classic hardcore yet.

@Tercioo : it seems that the client contains a lot of merges code from retail

**Comment by Tercioo** [comment]
k, will you change the framework then?

**Comment by kriminy** [comment]
> ![image](https://user-images.githubusercontent.com/9000280/250377771-bb3d4c3f-cf54-4b58-a98b-7a20a942d937.png) Is the wow classic era PTR?

Yes, the TOC is 1.14.4.

**Comment by cont1nuity** [comment]
Should be fixed with the next alpha.
