### ISSUE TITLE
Personal Resource Bar disappears when I /reload or log in

### ISSUE THREAD

**Issue by Laraque123** [Tercioo/Plater-Nameplates#177]
**Game and Plater version**
Which is the game version and Plater version you're using?
Plater-v561.4-Retail - DF v450 - 10.1.5

I am using this Plater Profile from Quazii: https://quazii.com/dragonflight-plater-nameplates-profile/

**Describe the bug**
Under the Blizzard Options Menu, I have "Personal Resource Display" turned on with "Show Special Resources on Targets".  I then configured the position of the "Personal Bar" within the Plater Options.  Both Health Bar and Power Bar are not enabled so it only shows my characters Resources (in this case on my DK it is his runes).  I can then play like this just fine and it works great.

Then if I /reload or if I log out and back in, the Personal Resource showing his Runes is gone.  I can get it to show up again by going to Plater Options "Combo Points" tab, then turning on and then off "Use Plater Resources".

- Steps to Reproduce (what did you do to make the bug happen):
If I /reload or if I log out and back in, the Personal Resource showing his Runes is gone. 

- Result (what happens when you follow the steps above):
The Personal Resource showing his Runes is gone until I go to Plater Options "Combo Points" tab, then turning on and then off "Use Plater Resources", then it works properly again.

- Expected (what you think the expected behavior would be when following the steps):
The UI should not change by logging out and back in.

- When the bug started (a date, wow path release, details update, etc)?
2023/07/28, but this is also the first date I used this setting.

- Additional information:

**Lua Error**
n/a

**Screenshots**
Can provide by request if there is something specific you want to see.

**Other Information**
n/a

**Comment by cont1nuity** [comment]
Screenshots of the resources, blizzard options, plater general settings. personal bar and combo points tab please.
