### ISSUE TITLE
Enemy player frames not change (not working)

### ISSUE THREAD

**Issue by Mithras2801** [Tercioo/Plater-Nameplates#179]
**Game and Plater version**
Which is the game version and Plater version you're using?
Latest alpha version : Plater-Plater-v561.4-9-g710f3a9 on curse
Ingame: Plater-v561.4-9-g710f3a9-Retail - DF v457 - 10.1.5

**Describe the bug**
Use option nameplates and only working on friendly target. No on Enemy in city (valdraken etc)

**Lua Error**
No lua

**Screenshots**
![Enemy player](https://github.com/Tercioo/Plater-Nameplates/assets/6137838/c3f46966-4e78-4dfd-afff-099eccf6cca1)

**Comment by cont1nuity** [comment]
Blizzard does not provide enemy faction nameplates in sanctuaries (larger cities), so nameplate addons cannot work on those.
