### ISSUE TITLE
Buff special "Show Timer" toggle doesn't work

### ISSUE THREAD

**Issue by BlartVersenwald** [Tercioo/Plater-Nameplates#182]
**Game and Plater version**
Plater-v564.2-Retail - DFv468 - 10.1.7

**Describe the bug**
Buff special "Show Timer" toggle doesn't work, timer is always shown.

**Comment by cont1nuity** [comment]
Works perfectly fine on my end.
I suggest trying with only Plater enabled and a default profile.
This might be due to some mod from the modding tab or OmniCC or similar addons.

**Comment by BlartVersenwald** [comment]
You're right, It works fine with default profile, but not with modified with omnicc enabled. So problem is just something there, I believe. Auras (buffs/debuffs) works just fine (timers through omnicc, not plater), but not ExtraIconRow.

**Comment by cont1nuity** [comment]
Any screenshot?
Usually that setting won't apply for OmniCC timers, just for the plater default one.

**Comment by BlartVersenwald** [comment]
Default profile
![Screenshot 2023-09-18 195021](https://github.com/Tercioo/Plater-Nameplates/assets/80219283/837522f6-3fc8-41e1-95fd-b3e5f1a66841)

Modified
![Screenshot 2023-09-18 194730](https://github.com/Tercioo/Plater-Nameplates/assets/80219283/9748c8b3-53e3-4975-beab-9f078f0f1e9e)

**Comment by cont1nuity** [comment]
And on that second one the timer is disabled in the options?
No mods on the modding tab that change anything for timers?

**Comment by BlartVersenwald** [comment]
Default profile
![Screenshot 2023-09-19 001958](https://github.com/Tercioo/Plater-Nameplates/assets/80219283/86c280d7-1e9b-42e7-8f5a-9d5b8cfcacd5)

Modified
![Screenshot 2023-09-19 001607](https://github.com/Tercioo/Plater-Nameplates/assets/80219283/3fd5c88d-ebe2-45c5-aef7-3bfccd7ff538)

Same settings with Omnicc (default one)

**Comment by BlartVersenwald** [comment]
Thank you, found one. It was "Buff Special Mod".
