### ISSUE TITLE
WoW Classic Era Update [Version 1.14.4]

### ISSUE THREAD

**Issue by maximus210793** [Tercioo/Plater-Nameplates#184]
Hi,
first of all, I want to say great adddon!
Could you update it to the latest Classic Era Game Version of 1.14.4?
Would be awesome, thanks a lot in advance!

**Comment by cont1nuity** [comment]
Is there any functionality broken?

**Comment by maximus210793** [comment]
Currently working, just a version upgrade would be great to 1.14.4

**Comment by cont1nuity** [comment]
That is done in the alpha versions and will be released.
