### ISSUE TITLE
Transparency with "Out of Range + Isn't Your Target" is bugged

### ISSUE THREAD

**Issue by orblazer** [Tercioo/Plater-Nameplates#185]
**Game and Plater version**
Plater-v566-Retail - DF v482 - 10.2.0

**Describe the bug**
The transparency from "Out of Range" and "Isn't Your Target" seem to be added that render frame almost invisible.

- Steps to Reproduce (what did you do to make the bug happen):
  - Enable "Out of Range + Isn't Your Target" in General Settings
  - Set "Enable for Enemies" to true
  - Set "Default Transparency" (for enemies) to 1
  - See transparency of other targets

- Result (what happens when you follow the steps above):
![WoWScrnShot_111623_232732](https://github.com/Tercioo/Plater-Nameplates/assets/1344792/a81212e3-2b82-43a1-918c-9933cf91789d)

- Expected (what you think the expected behavior would be when following the steps):
Have same transparency then when i'm not in combat.
![WoWScrnShot_111623_233141](https://github.com/Tercioo/Plater-Nameplates/assets/1344792/31fcd7b0-0600-45ca-a11f-61703b831b55)

- When the bug started (a date, wow path release, details update, etc)?
With patch "10.2.0.52188" appear Thursday 16, November 2023 in afternoon.

**Other Information**
Profile : https://wago.io/gw4KM1mRd

**Comment by Skullcan** [comment]
Might be related to this?
https://github.com/WeakAuras/WeakAuras2/issues/4713

**Comment by cont1nuity** [comment]
> WeakAuras/WeakAuras2#4713

Yes.
There will be updates. Likely tomorrow.
As it is a shared library, updating WA might help once they push out a fix.

**Comment by Sebastian1989101** [comment]
+1 (just to get a notification when this issue is fixed)

**Comment by cont1nuity** [comment]
Please update to the latest alpha version and verify.

**Comment by sindredl** [comment]
Can confirm that the newest alpha works as intended again 👍
