### ISSUE TITLE
IsSpellInRange(); lua error - Plater-v569-Retail - DF v482 - 10.2.0

### ISSUE THREAD

**Issue by Larsy93** [Tercioo/Plater-Nameplates#186]
**Game and Plater version**
Which is the game version and Plater version you're using?
Plater version info:
Plater-v569-Retail - DF v482 - 10.2.0

- When the bug started (a date, wow path release, details update, etc)?
Today

**Lua Error**
6x Plater/Plater.lua:817: IsSpellInRange(): Invalid spell slot
[string "=[C]"]: in function `IsSpellInRange'
[string "@Plater/Plater.lua"]:817: in function `rangeChecker'
[string "@Plater/Plater.lua"]:852: in function `CheckRange'
[string "@Plater/Plater.lua"]:6626: in function `UpdateTarget'
[string "@Plater/Plater.lua"]:7747: in function `UpdatePlateFrame'
[string "@Plater/Plater.lua"]:3597: in function `func'
[string "@Plater/Plater.lua"]:3850: in function <Plater/Plater.lua:3846>

Locals:
(*temporary) = nil
(*temporary) = "nameplate1"

**Comment by cont1nuity** [comment]
Should be fixed in the latest alpha. Related to #185
