### ISSUE TITLE
Healer spec (druid/sham) transparency issues on range check

### ISSUE THREAD

**Issue by gollumeo** [Tercioo/Plater-Nameplates#187]
**Game and Plater version**
Plater-v569-Retail - DF v482 - 10.2.0

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
Swap to healer spec (issue has been noticed on rsham & rdruid). Toggle "Units Out of Your Range" in the "Transparency Is Used for" section, and enable for ennemies "Transparency Amount Per Frame (enemies)"

- Result (what happens when you follow the steps above):
![image](https://github.com/Tercioo/Plater-Nameplates/assets/109650634/3dd4e0ff-488d-4c20-a5c1-9d227f599aed)

- Expected (what you think the expected behavior would be when following the steps):
![image](https://github.com/Tercioo/Plater-Nameplates/assets/109650634/dd00288f-20b5-4515-a2fe-1b95992ac848) (swapped to a dps spec)

- When the bug started (a date, wow path release, details update, etc)?
Today!

- Additional information:

**Lua Error**
Post here lua errors, if you aren't getting any, use */console scriptErrors 1*

**Screenshots**
Post images of the bug if necessary.

**Other Information**
If necessary, add more info here.

**Comment by cont1nuity** [comment]
Should be fixed in the latest alpha. Related to #185

**Comment by gollumeo** [comment]
Doesn't seem to be, on my side. 
Version: 
Plater-v569-Retail - DF v482 - 10.2.0

Result: 
![image](https://github.com/Tercioo/Plater-Nameplates/assets/109650634/4a6bfd45-2f90-4b5a-afb9-1a8a171587d4)

Expected result: 
![image](https://github.com/Tercioo/Plater-Nameplates/assets/109650634/b859de95-edfb-46cf-8ac4-9fb89e2c2c57)

**Comment by cont1nuity** [comment]
> Plater-v569-Retail - DF v482 - 10.2.0

This is a release version, not the latest alpha.

**Comment by gollumeo** [comment]
I'm sorry, I might be retarded, but where/how do I get that latest alpha though? 😅

**Comment by cont1nuity** [comment]
On your usual updater or directly from CF or wago. Ensure to list all files or switch to release type "alpha"
