### ISSUE TITLE
Channeled not showing on SOD classic

### ISSUE THREAD

**Issue by olepg** [Tercioo/Plater-Nameplates#193]
Season of discovery
plater-v571-classic -df v497 - 1.15.0

I can't see channeled abilities as a castbar when mages use channeled spells.

- Steps to Reproduce (what did you do to make the bug happen):
Have a mage cast a channeled ability

- Result (what happens when you follow the steps above):
I dont see the cast bar

- Expected (what you think the expected behavior would be when following the steps):
I expect to see a cast/channeled bar

**Screenshots**
![image](https://github.com/Tercioo/Plater-Nameplates/assets/27433531/5a2d8503-2d40-4afb-b90f-c5473743f63b)

**Comment by cont1nuity** [comment]
There's nothing we can do about that, as the blizzard api does not return any info. See https://github.com/Stanzilla/WoWUIBugs/issues/516

**Comment by olepg** [comment]
Thank you for answer :-) 
Could't find anything on google.
