### ISSUE TITLE
Plater keeps getting disabled on login

### ISSUE THREAD

**Issue by selenelunaedge** [Tercioo/Plater-Nameplates#207]
**Game and Plater version**
Game Version: 10.2.7 (55261) (Release x64)
Plater version info:
Plater-v582-Retail - DF v543 - 10.2.7

Plater keeps getting disabled on login, on any character.
It has been going on for months and while chat prints a conflict message if ElvUI's Nameplates module is enabled, it happens regardless of that, or ElvUI being enabled at all.

**Comment by cont1nuity** [comment]
What exactly do you mean by "getting disabled"? Any screenshots or a bit more detailed information would be useful.

**Comment by selenelunaedge** [comment]
I just recorded a couple of videos!

I use Plater for all my characters. In [Video #1](https://youtu.be/vtIpyAVrxVs) I log into a Druid I just played yesterday and Plater is disabled. I reenable it, logout, log into a Priest and Plater is disabled again.

[Video #2](https://youtu.be/s8R0rN6Xhqg) is more of the same, but I go back and forth between the same two characters and Plater keeps getting automatically disabled each time.

I have ElvUI Nameplates already disabled on the characters, and the issue seems "infectious": I first noticed it last October when I logged into multiple characters daily to farm the event mount. Once this issue happened on one character, it'd happen on every subsequent character. I alternated going down and up the list and regardless of order once it happened on one character it kept happening, even on my main.

**Comment by cont1nuity** [comment]
Video #1 is listed as private, I cannot view it.
In video #2 you clearly have another nameplate addon active.
Ensure to disable all other nameplate addons and to disable the whole nameplate module in ElvUI.
This is not caused by plater but by another addon (presumably a nameplate addon).

**Comment by cont1nuity** [comment]
No reply since three weeks.
