### ISSUE TITLE
Ghost Auras throwing error

### ISSUE THREAD

**Issue by AngelosNaoumis** [Tercioo/Plater-Nameplates#209]
**Game and Plater version**
Which is the game version and Plater version you're using?
Full `/plater version` output please.
Plater-v-582-Retail DF v547 - 10.2.7

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
Open plater settings in Ghost Auras

- Result (what happens when you follow the steps above):
Throws lua error

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

- Expected (what you think the expected behavior would be when following the steps):
No error to be shown

- When the bug started (a date, wow path release, details update, etc)?
I have been absent for very long time, so not sure

- Additional information:

**Lua Error**
Post here lua errors, if you aren't getting any, use */console scriptErrors 1*
Message: Interface/AddOns/Plater/Plater_GhostAurasFrames.lua:48: bad argument #1 to 'pairs' (table expected, got nil)
Time: Tue Jul 16 18:47:54 2024
Count: 1
Stack: Interface/AddOns/Plater/Plater_GhostAurasFrames.lua:48: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Interface/AddOns/Plater/Plater_GhostAurasFrames.lua"]:48: in function `SetSpec'
[string "@Interface/AddOns/Plater/Plater_GhostAurasFrames.lua"]:200: in function <Interface/AddOns/Plater/Plater_GhostAurasFrames.lua:199>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Plater/libs/DF/tabcontainer.lua"]:141: in function `SelectTabByIndex'
[string "@Interface/AddOns/Plater/libs/DF/tabcontainer.lua"]:348: in function <Interface/AddOns/Plater/libs/DF/tabcontainer.lua:348>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/Plater/libs/DF/fw.lua"]:4630: in function `CoreDispatch'
[string "@Interface/AddOns/Plater/libs/DF/button.lua"]:733: in function <Interface/AddOns/Plater/libs/DF/button.lua:669>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Screenshots**
Post images of the bug if necessary.

**Other Information**
It happens if you are without selected spec

**Comment by AngelosNaoumis** [comment]
This happens if you are lvl 10 without spec

**Comment by cont1nuity** [comment]
Which class and race is this happening on?

**Comment by AngelosNaoumis** [comment]
Sorry for late reply, it was human in my case but i think all of them

**Comment by cont1nuity** [comment]
> Sorry for late reply, it was human in my case but i think all of them

And which class?

**Comment by AngelosNaoumis** [comment]
Rogue
