### ISSUE TITLE
Grey bar showing above the targeted mob

### ISSUE THREAD

**Issue by jadinm** [Tercioo/Plater-Nameplates#213]
**Game and Plater version**

Game:
wow retail 11.0.0.55824

`/plater version` output:
Plater-v583-Retail - DF v551 - 11.0.0

**Describe the bug**

- Steps to Reproduce (what did you do to make the bug happen):

Targeting a hostile mob.

- Result (what happens when you follow the steps above):

This adds a grey bar above the usual nameplate offered by the plugin.

- Expected (what you think the expected behavior would be when following the steps):

No grey bar above the nameplate as it was before

- When the bug started (a date, wow path release, details update, etc)?

The day of the pre-patch release of this week

**Lua Error**

*/console scriptErrors 1*

No lua error seen

**Screenshots**

![Capture d'écran 2024-07-25 140904](https://github.com/user-attachments/assets/57cc7797-33b3-48a3-8efd-9694ecd0cd8b)

**Comment by cont1nuity** [comment]
Are you playing monk and do you have "resources on target" activated? It looks like the stagger bar.

**Comment by jadinm** [comment]
Indeed I am a monk and indeed the green part seems to match my stagger bar.
But this option is disabled (see capture).

![Capture d'écran 2024-07-25 144604](https://github.com/user-attachments/assets/a141b03e-b96a-4114-be3d-817d4d9bb3f4)

Enabling it shows no difference (still seeing it) and disabling it again does not remove the bar.

**Comment by jadinm** [comment]
FYI, still happening on Plater-v583a-Retail

**Comment by jadinm** [comment]
Resetting all the options to default fixed my issue :-)
