### ISSUE TITLE
range indicator (transparency) does not work properly

### ISSUE THREAD

**Issue by Breakerzeus** [Tercioo/Plater-Nameplates#215]
**Game and Plater version**
Game: 11.0
Plater: Plater-v583a-Retail - DF v551 - 11.0.0

**Describe the bug**
on my DH I noticed that the range indicator (transparent bars when out of range) does not work properly. even when mobs hit me in melee the bars are still transparent. then I noticed that the set range is 30y and I changed it to 40y. that worked and I thought that maybe the DH does not have a 30y ability so it can't measure correctly.

But now I'm on my mage and there the issue still happens. the 40y are set on my mage and he definitly has some 40y abilities, so it should work, right? but it doesn't. when I set it to 30y again, then it seems to work.
So I'm sure that there is something wrong with the range check.

- Steps to Reproduce (what did you do to make the bug happen): change settings between 30y and 40y and check on enemies

- Result (what happens when you follow the steps above): mobs are shown out of range that in reality are in range

- Expected (what you think the expected behavior would be when following the steps): range check works properly

- When the bug started (a date, wow path release, details update, etc)? 11.0 patch

- Additional information:

**Lua Error**
Post here lua errors, if you aren't getting any, use */console scriptErrors 1*

**Screenshots**
40y setting:
![grafik](https://github.com/user-attachments/assets/1c9d5fe2-ee75-474d-85e8-470220611a01)

30y setting:
![grafik](https://github.com/user-attachments/assets/e543f6c3-fe5b-4567-b492-21dab311a89f)

**Other Information**
If necessary, add more info here.

**Comment by cont1nuity** [comment]
Known issue. Will be fixed with https://github.com/WeakAuras/LibRangeCheck-3.0/pull/30 and the next plater version afterwards.
