### ISSUE TITLE
Sticky Interact CVar issue

### ISSUE THREAD

**Issue by Yakehira** [Tercioo/Plater-Nameplates#217]
In my own addon Better Fishing i set CVars dynamically, but if a user decides to fish and /reload while doing so this will cause some quirk in plater as it checks for the cvar.

See: https://github.com/Tercioo/Plater-Nameplates/blame/2496475939a05df2907291e1f50a66fcfcc7b0ad/options/Plater_O_Advanced.lua#L194

Easy repro
1. Go to Advanced settings in plater and make sure this is off.
![image](https://github.com/user-attachments/assets/5f2a1791-884b-467c-b522-711f23e589f5)

2.  `/run SetCVar("SoftTargetInteract", 3)`
3. `/reload`
3. Check in the wow Settings if Enable Interact Key is enabled, it will not be!
4. `/reload` again
5. Check again in settings, Enable Interact Key is now turned on, as well as in Plater is now sticky
6. If a user decides to turn off Enable Interact Key over the Settings rather than plater now, it will never properly work unless disabled over plater or plater being disabled.

![image](https://github.com/user-attachments/assets/8913363a-cce2-4c24-a3ec-95349772c49b)

**Comment by cont1nuity** [comment]
The recently released changes should improve the setting to no longer be sticky.

**Comment by Yakehira** [comment]
Remains being very sticky and can only be toggled in plater settings, toggling it in the Default UI doesn't appear to work.

Root of the cause seems to be https://github.com/Tercioo/Plater-Nameplates/blob/2496475939a05df2907291e1f50a66fcfcc7b0ad/Plater.lua#L1536 which is case sensitive, but it needs to be entirely case-insensitive, the settings write `softTargetInteract`, not `SoftTargetInteract`.

**Comment by cont1nuity** [comment]
Goddamn blizzard not honoring their own names... You are likely right about the case sensitivity. I'll likely need to migrate the whole storage to lowercase instead this case, which sucks.

**Comment by cont1nuity** [comment]
This should ensure it is recognized properly.

**Comment by Yakehira** [comment]
Yeah that appears to work now properly, thanks :)
