### ISSUE TITLE
May I ask how to resolve this error message

### ISSUE THREAD

**Issue by wunk88** [Tercioo/Plater-Nameplates#219]
Message: Interface/AddOns/Plater/Plater_Auras.lua:1126: invalid order function for sorting
Time: Sun Aug 11 16:10:59 2024
Count: 1659
Stack: Interface/AddOns/Plater/Plater_Auras.lua:1126: invalid order function for sorting
[string "@Interface/AddOns/Plater/Plater_Auras.lua"]:1126: in function AlignAuraFrames'
[string "@Interface/AddOns/Plater/Plater.lua"]:6365: in function <Interface/AddOns/Plater/Plater.lua:6182>

Locals: self = NamePlate34PlaterUnitFrameBuffFrame2 {
 unitFrame = NamePlate34PlaterUnitFrame {
 }
 amountAurasShown = 4
 NextAuraIcon = 5
 isNameplate = true
 namePlateUnitReaction = 5
 HasDebuff = false
 unit = "nameplate4"
 HasBuff = true
 healthBar = NamePlate34PlaterUnitFrameHealthBar {
 }
 FadeAnimation = AnimationGroup {
 }
 AuraCache = <table> {
 }
 Name = "Secondary"
 BuffFrame1 = NamePlate34PlaterUnitFrameBuffFrame1 {
 }
 PlaterBuffList = <table> {
 }
}
profile = <table> {
 focus_as_target_alpha = false
 ui_parent_buff_special_level = 10
 aura_breakline_space = 4
 aura_show_only_short_dispellable_on_players = true
 npcs_renamed = <table> {
 }
 saved_cvars_last_change = <table> {
 }
 url = "https://wago.io/LTa_SLFLs/30"
 hover_highlight = true
 blizzard_nameplate_font_override_enabled = false
 show_shield_prediction = true
 aura_border_thickness_personal = 1
 indicator_raidmark_scale = 0.750000
 stacking_nameplates_enabled = true
 aura2_y_offset = 39.589996
 spell_animations_scale = 1.250000
 aura_timer_text_anchor = <table> {
 }
 extra_icon_caster_size = 8
 buffs_on_aura2 = true
 health_selection_overlay = "11StripesOverlay2"
 expansion_triggerwipe = <table> {
 }
 show_aggro_glow = true
 cast_statusbar_color_nointerrupt = <table> {
 }
 show_interrupt_author = true
 bossmod_support_bars_enabled = false
 hide_blizzard_castbar = false
 extra_icon_cooldown_reverse = true
 health_cutoff_extra_glow = false
 use_ui_parent_just_enabled = false
 npc_cache = <table> {
 }
 extra_icon_timer_decimals = false
 aura_cooldown_reverse = true
 indicator_anchor = <table> {
 }
 hide_name_on_game_objects = true
 health_selection_overlay_alpha = 0.300000
 aura_stack_shadow_color = <table> {
 }
 minor_height_scale = 1.000000
 culling_distance = 100
 reopoen_options_panel_on_tab = false
 blizzard_nameplate_large_font_outline = "OUTLINE"
 blizzard_nameplate_font_outline = "OUTLINE"
 aura_padding = 3.500000
 indicator_worldboss = true
 last_news_time = 1652261772
 range_check_power_bar_alpha_friendlies = 1
 cast_statusbar_fadeout_time = 0.500000
 aura_stack_shadow_color_offset = <table> {
 }
 aura_stack_size = 8
 cast_audiocue_cooldown = 0.250000
 aura_timer_decimals = false
 range_check_health_bar_alpha = 1
 aura_height2 = 15
 aura_show_crowdcontrol = true
 castbar_target_shadow_color_offset = <table> {
 }
 cast_colors = <table> {
 }
 health_cutoff = true
 aura_border_colors = <table> {
 }
 ui_parent_cast_strata = "BACKGROUND"
 class_colors = <table> {
 }
 enable_masque_support = false
 show_healthbars_on_softinteract = true
 extra_icon_anchor = <table> {
 }
 extra_icon_wide_icon = false
 ui_parent_buff2_strata = "BACKGROUND"
 use_playerclass_color = true
 range_check_alpha = 0.800000
 semver = "1.1.7"
 aura_border_thickness = 1
 health_cutoff_hide_divisor = false
 aura_frame2_anchor = <table> {
 }
 use_name_translit = false
 cast_statusbar_texture = "A04"
 auto_toggle_friendly = <table> {
 }
 indicator_faction = false
 castbar_icon_x_offset = 0
 show_softinteract_icons = true
 debuff_show_cc = true
 show_healthbars_on_not_attackable = false
 extra_icon_show_purge = true
 transparency_behavior = 4
 spell_animations = true
 debuff_show_cc_border = <table> {
 }
 aura_consolidate = true
 shadowMode = 1
 auto_toggle_combat_enabled = false
 extra_icon_width = 13
 health_statusbar_texture = "A04"
 hook_auto_imported = <table> {
 }
 extra_icon_border_color = <table> {
 }
 minor_width_scale = 1.000000
 castbar_target_text_size = 11
 captured_spells = <table> {
 }
 aura_frame1_anchor = <table> {
 }
 range_check_cast_bar_alpha_friendlies =**Game and Plater version**
Which is the game version and Plater version you're using?
Full `/plater version` output please.

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):

- Result (what happens when you follow the steps above):

- Expected (what you think the expected behavior would be when following the steps):

- When the bug started (a date, wow path release, details update, etc)?

- Additional information:

**Lua Error**
Post here lua errors, if you aren't getting any, use */console scriptErrors 1*

**Screenshots**
Post images of the bug if necessary.

**Other Information**
If necessary, add more info here.

Is there an error in which module or script？

**Comment by cont1nuity** [comment]
You have not filled in any of the requested information. Please do so.
From a first guess: a broken aura reorder mod.

**Comment by wunk88** [comment]
It's indeed the issue you mentioned, thank you
The problem has been resolved
