### ISSUE TITLE
Plater Mod TotalRP3 Nameplates code throwing caught lua error for IsAddOnLoaded

### ISSUE THREAD

**Issue by icbat** [Tercioo/Plater-Nameplates#223]
**Game and Plater version**
Which is the game version and Plater version you're using?
Full `/plater version` output please.

Plater-v583b-Retail - DF v557 - 11.0.2

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):

I had previously installed TotalRP3 alongside Plater, but do not currently have it installed. Seeing any nameplate, friendly or enemy, will throw this error in chat, as well as on load into the world.

- Result (what happens when you follow the steps above):

Very often, maybe every time Plater shows a nameplate, the error text shown in the screenshot below is displayed in the chat box.

- Expected (what you think the expected behavior would be when following the steps):

No error messages in chat.

- When the bug started (a date, wow path release, details update, etc)?

Right with 11.0.2 release.

- Additional information:

**Lua Error**
Post here lua errors, if you aren't getting any, use */console scriptErrors 1*

Not getting any, even with the above slash command.

**Screenshots**
Post images of the bug if necessary.

Nameplate Added event message(s):
![image](https://github.com/user-attachments/assets/d84214aa-4592-4aae-b63a-e77127b60375)

Initialization error:
![image](https://github.com/user-attachments/assets/2e633297-a468-46e2-a0b1-4f42f6550a5b)

**Other Information**
If necessary, add more info here.

Please let me know what other info I can provide; I'm not really sure how to troubleshoot this one.

**Comment by cont1nuity** [comment]
This is not an issue with Plater, but with a mod in your profile that was automatically added by TotalRP3 at some point.
Disable or remove the mod on the plater modding tab.

**Comment by icbat** [comment]
Thank you for the speedy response! That's a neat feature I've never had to care about before.
