### ISSUE TITLE
Hella sorry

### ISSUE THREAD

**Issue by Theguyxd** [Tercioo/Plater-Nameplates#226]
Hey, I'm sorry. I know this is not the right place to ask this. But how do I empty the trash bin for mods I've removed? Does it do it on its own or am I just stupid and missing something? Cheers.

**Comment by Tercioo** [comment]
30 days


------ Original Message ------
From "Theguyxd" ***@***.******@***.***>>
To "Tercioo/Plater-Nameplates" ***@***.******@***.***>>
Cc "Subscribed" ***@***.******@***.***>>
Date 26-Aug-24 3:16:53 PM
Subject [Tercioo/Plater-Nameplates] Hella sorry (Issue #226)


Hey, I'm sorry. I know this is not the right place to ask this. But how do I empty the trash bin for mods I've removed? Does it do it on its own or am I just stupid and missing something? Cheers.
