### ISSUE TITLE
Aura Lua Error

### ISSUE THREAD

**Issue by doadin** [Tercioo/Plater-Nameplates#227]
**Game and Plater version**
Which is the game version and Plater version you're using?
Full `/plater version` output please.
Plater version info:
Plater-v585b-Retail - DF v565 - 11.0.2

**Describe the bug**
Happened after hitting Arcane Torrent with a boss with a buff on it.

**Lua Error**
20x Plater Script Aura is Shield [P] OnUpdate error: 
Mod/Script URL: 
Plater-v585b-Retail - DF v565 - 11.0.2
[string "UpdateCode for Aura is Shield [P]"]:12: attempt to call global 'UnitAuraSlots' (a nil value)
[string "UpdateCode for Aura is Shield [P]"]:12: in function <[string "UpdateCode for Aura is Shield [P]"]:1>
[string "=[C]"]: ?
[string "@Plater/Plater.lua"]:11121: in function `ScriptRunOnUpdate'
[string "@Plater/Plater_Auras.lua"]:1905: in function `RunScriptTriggersForAuraIcons'
[string "@Plater/Plater.lua"]:6381: in function <Plater/Plater.lua:6195>

Locals:
Skipped (In Encounter)

**Screenshots**
Post images of the bug if necessary.

**Other Information**
If necessary, add more info here.

**Comment by cont1nuity** [comment]
This should be resolved since daa5277
