### ISSUE TITLE
Add info about LibCustomGlow support in Plater_ScriptingPanels.lua

### ISSUE THREAD

**Issue by Caskol** [Tercioo/Plater-Nameplates#228]
Hi! I tried to find any info about changing glow effects on some auras and found that plater has those api functions, which wasn't wroted about in Plater_ScriptingPanels.lua file. There is some interesting features that wasn't described in this file and may be very useful. There is [**link to pull-request**](https://github.com/Tercioo/Plater-Nameplates/pull/36) when those functions was added. 

There is some people who doesn't like new Blizzard glow effects added in 10.1.5 and they may use these functions to display glows as they want (for example, old glow effect by using Plater.StartButtonGlow(self)).

**Comment by cont1nuity** [comment]
Done.
