### ISSUE TITLE
recurring exception in combat

### ISSUE THREAD

**Issue by saggymac** [Tercioo/Plater-Nameplates#232]
**Game and Plater version**
11.0.2 56461 (x64)
Plater-v587-Retail - DF v565 - 11.0.2

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):

Happens in combat.  It is not clearly tied to an action from me.  

- Result (what happens when you follow the steps above):

Exception is thrown (see text below).  When I close the exception, it comes back very quickly.  Essentially non-stop.  So it is rather debilitating and I end up disabling the addon.

- Expected (what you think the expected behavior would be when following the steps):

No exception.

- When the bug started (a date, wow path release, details update, etc)?

I noticed it with TWW (pre-release).  Waited for a few patch releases as some issues with a new launch are expected.  But issue remains.

LUA Error
------------------------------------

Message: [string "Constructor for Interrupt not ready Cast Co..."]:62: attempt to call global 'GetSpellCooldown' (a nil value)
Time: Fri Sep  6 08:56:50 2024
Count: 2
Stack: [string "Constructor for Interrupt not ready Cast Co..."]:62: attempt to call global 'GetSpellCooldown' (a nil value)
[string "Constructor for Interrupt not ready Cast Color"]:62: in function `GetCastColor'
[string "@Interface/AddOns/Details/Libs/DF/unitframe.lua"]:1042: in function `UpdateCastColor'
[string "@Interface/AddOns/Details/Libs/DF/unitframe.lua"]:1530: in function `UpdateCastingInfo'
[string "@Interface/AddOns/Details/Libs/DF/unitframe.lua"]:1544: in function `eventFunc'
[string "@Interface/AddOns/Details/Libs/DF/unitframe.lua"]:1278: in function <Interface/AddOns/Details/Libs/DF/unitframe.lua:1261>
[string "=[C]"]: ?

Locals: self = NamePlate2PlaterUnitFrameCastBar {
 isNamePlate = true
 barBorderTextureForMask = Texture {
 }
 BorderShield = Texture {
 }
 extraBackground = Texture {
 }
 HookList = <table> {
 }
 unit = "nameplate2"
 canInterrupt = false
 Colors = <table> {
 }
 unitFrame = NamePlate2PlaterUnitFrame {
 }
 IsCastBar = true
 fadeInAnimation = AnimationGroup {
 }
 spellTexture = 136025
 casting = true
 stagePips = <table> {
 }
 spellName = "Fracturing Leap"
 maxValue = 3
 barTexture = Texture {
 }
 fadeOutAnimation = AnimationGroup {
 }
 flashAnimation = AnimationGroup {
 }
 Icon = Texture {
 }
 lazyUpdateCooldown = 0.100000
 value = 0
 spellEndTime = 386252.495000
 percentText = FontString {
 }
 spellStartTime = 386249.495000
 castID = "Cast-3-3776-2552-57-444692-008ADAFC0A"
 spellID = 444692
 PlateFrame = NamePlate2 {
 }
 FrameOverlay = NamePlate2PlaterUnitFrameCastBarOverlayFrame {
 }
 Settings = <table> {
 }
 empowered = false
 PixelSnapDisabled = true
 Spark = Texture {
 }
 FadeAnimation = AnimationGroup {
 }
 displayedUnit = "nameplate2"
 CastBarEvents = <table> {
 }
 customborder = Frame {
 }
 castColorTexture = NamePlate2PlaterUnitFrameCastBarCastColor {
 }
 TargetName = FontString {
 }
 FrameDownlayer = NamePlate2PlaterUnitFrameCastBarDownlayerFrame {
 }
 _points = <table> {
 }
 interruptSpellId = 1766
 flashTexture = Texture {
 }
 Text = FontString {
 }
 barTextureMask = MaskTexture {
 }
 WidgetType = "castBar"
 ThrottleUpdate = 0
 background = Texture {
 }
}
interruptCD = 0
(*temporary) = nil
(*temporary) = 1766
(*temporary) = "attempt to call global 'GetSpellCooldown' (a nil value)"
kickReadyInTimeGraceTime = 0.500000
kickReadyInTimeColor = "#00D1FF"
noKickReadyColor = "#eaeaea"

**Comment by cont1nuity** [comment]
Not an error in plater, but in one of the mods you're using. Modding tab in plater. Name is in the first line of the error. Update, disable or remove that mod.

**Comment by saggymac** [comment]
Brilliant, thank you.  Reset to default profile; deleted old profile.  Forgot I was using a profile from long ago.
