### ISSUE TITLE
Debuff Graphics Not Displaying Correctly

### ISSUE THREAD

**Issue by ComfortableDoug** [Tercioo/Plater-Nameplates#245]
**Game and Plater version**
Cataclysm Version 4.4.1 (57294) (Release x64)
Plater-v595-Cata - DF v575 - 4.4.1

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen): Installing the latest version of Cataclysm and the associated new HD texture pack

- Result (what happens when you follow the steps above): Graphics for debuffs on plater appear corrupted or garbled instead of using the correct images

- Expected (what you think the expected behavior would be when following the steps): The debuffs should show up as the correct images

- When the bug started (a date, wow path release, details update, etc)? 10/29/24

- Additional information: The buffs in the image are Living Bomb, Critical Mass, and Combustion

**Lua Error**
Post here lua errors, if you aren't getting any, use */console scriptErrors 1*

**Screenshots**
![image](https://github.com/user-attachments/assets/04309756-aa92-4435-ab16-be93bc000646)

**Other Information**
If necessary, add more info here.

**Comment by cont1nuity** [comment]
It seems like the swipe animation used for "blank" swipes has been changed and is broken for the high resolution pack. Please change it for now on the lower right of the Buff Settings tab.

**Comment by ComfortableDoug** [comment]
Thanks! Looking closer it appears to be just Texture 5 that is a problem:
![image](https://github.com/user-attachments/assets/dbdd75af-2216-4ad0-8248-71b0935f7ac3)

**Comment by cont1nuity** [comment]
Fixed within the latest alpha version.
