### ISSUE TITLE
Demoralizing Roar shows as CC on cata classic

### ISSUE THREAD

**Issue by lordblackadder** [Tercioo/Plater-Nameplates#248]
**Game and Plater version**
Plater-v595-Cata - DF v580 - 4.4.1

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
Just have someone (you or anyone else) cast Demoralizing Roar on a target on cata classic
- Result (what happens when you follow the steps above):
Demo roar is shown as a CC on the right of the nameplate (ExtraIconRow) instead of above it like non-CC debuffs.
- Expected (what you think the expected behavior would be when following the steps):
It should be the listed above the nameplate.
- When the bug started (a date, wow path release, details update, etc)?
Unknown.
- Additional information:
Demoralizing Roar on cata classic uses the same spell id as Incapacitating Roar on retail (id 99). It appears that somehow it is still shown as if it was on mainline WoW.

**Screenshots**
![image](https://github.com/user-attachments/assets/f9a3995b-0894-4224-982f-da11defb3b23)

**Comment by cont1nuity** [comment]
@Tercioo this is rather for the Lib, no?

**Comment by lordblackadder** [comment]
This has been fixed since. Closing.
