### ISSUE TITLE
Is the head/feet nameplate anchor taken out of the game?

### ISSUE THREAD

**Issue by wwbrandon** [Tercioo/Plater-Nameplates#249]
Hey there,

Trying to use the split feature for hostile/friendly at head/feet for nameplates and it doesn't seem to work anymore. Was this feature removed from the game?

**Comment by cont1nuity** [comment]
Still working just fine here:
![image](https://github.com/user-attachments/assets/9b51dd68-c61e-4093-b12f-e1fafcee9148)

**Comment by wwbrandon** [comment]
I think you misunderstood- there are 3 options or at least used to be. There was an option for friendly at head and hostile at feet. It doesn't work in Plater anymore.

![image](https://github.com/user-attachments/assets/deb0d48f-b79a-4fa1-b61d-e5b48918c71d)
