### ISSUE TITLE
Feature Request - Nameplate scaling and alpha based on enemy (Neutral, Hostile etc.)

### ISSUE THREAD

**Issue by Vakke** [Tercioo/Plater-Nameplates#25]
Hello!

I've been using Tidy plates and then Threat plates for years now. Few days ago I saw Plater and tried it and I was immensively impressed right at the beginning. I imported the most starred profile from Wago and it had everything what was lacking for me from Threat plates. BUT.

I've been trying to change the sizes of nameplates based on enemies: neutral, normal hostiles, rares and elites and the transparency on based on the same reason. Am I able to do it at the moment and I'm just too unskilled or is it something I cannot even do at the moment?

My ideal situation would be that I would be able to resize nameplates when based on enemy units (neutral etc) when I'm in combat and not in combat. Also to change the transparency of the nameplates of those different units when I'm in combat and not. I'm not sure if I'm able to clarify this better but I'm looking for the same kind of ability to change these like the Threat plates have. I'll provide screenshots if you need and would want them. 

Best regards,
Vakke

**Comment by cont1nuity** [comment]
I have not tried it, but all should be achievable via mods, if you are using the "Use Custom Strata Channels" option. Might be a bigger mod, though.

**Comment by cont1nuity** [comment]
Friendly / Enemy alpha has been implemented. Size/scaling is tied to blizzard and can be changed via mods or scripts.
