### ISSUE TITLE
Plater doesn't have all strings localized

### ISSUE THREAD

**Issue by anon1231823** [Tercioo/Plater-Nameplates#253]
**Game and Plater version**
Which is the game version and Plater version you're using?
Full `/plater version` output please.

Plater-v596-Vanilla - DF v582 - 1.15.5

**Describe the bug**
Not all the strings are translated as you can see in the screenshot, even though curse localization table says spanish is 100% complete
https://legacy.curseforge.com/wow/addons/plater-nameplates/localization

**Screenshots**
![image](https://github.com/user-attachments/assets/10fdc54a-220c-4163-a82e-91fe4d9a38e2)

**Comment by cont1nuity** [comment]
Duplicate #110
