### ISSUE TITLE
Friendly NPC Title/Profession displayed on 

### ISSUE THREAD

**Issue by BaronessRuby** [Tercioo/Plater-Nameplates#261]
**Game and Plater version**
Which is the game version and Plater version you're using?
Full `/plater version` output please.
Plater-v598-Retail - DF v586 - 11.0.7

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
Enabling the Friendly NPC nameplate and interacting with a NPC that possess a Title, makes its title display on Friendly Player Nameplates while I'm in combat. 
Disabling the Module for Friendly NPC or selecting "Show : XXX (healthbars)" remove the bug.

- Result (what happens when you follow the steps above):
The title of previously interacted npcs display on Friendly Player Nameplates while I'm in combat.

- Expected (what you think the expected behavior would be when following the steps):
NPC title shouldn't be displayed on player nameplate when in combat.

- When the bug started (a date, wow path release, details update, etc)?
Unsure

- Additional information:
If I jump right in a combat without interacting with a NPC after a load or reload, the bug doesn't appear.
It doesn't need to be in range of any friendly npc to triggers, as long as I've interacting with one, the bug will appear later in any combat until a reload/loading screen

**Lua Error**
Post here lua errors, if you aren't getting any, use */console scriptErrors 1*

**Screenshots**
Post images of the bug if necessary.

Below we can see the NPC that I'm targetting, Suzie Vrilleboulon, with the title "<Spécliaste mécanique>", while the player "Gratounette" is beside her.
![Capture d'écran 2024-12-27 152357](https://github.com/user-attachments/assets/923ed7f4-1674-4a3c-8130-95aec3b79eab)

Below, while I'm in combat, the title gets duplicated and paste upon the displayed friendly player nameplate.
![Capture d'écran 2024-12-27 152351_crop](https://github.com/user-attachments/assets/6c4f4ee1-c77a-4d91-b8c2-4b37a28ab243)

**Other Information**
If necessary, add more info here.
As I've said above, interacting with the NPC is the key part of the bug. Just clicking on its nameplates doesn't trigger the bug. I've been using DialogueUI as a Addon for quests, conversations and others improvements for any interaction while right clicking NPCs, but even with it disabled, the bug continue to trigger itself.

**Comment by cont1nuity** [comment]
Please check for errors with BugSack (addon) and try to reproduce this with a default plater profile.

**Comment by BaronessRuby** [comment]
There was no errors shown with BugSack, but with default plater profile and diving inside the Lua code of one of the mods that comes bundled with a profile from Wago.io, i did see the problem where it was findling with unitFrame.ActorTitleSpecial.
Sincerely sorry for the inconvenience !
