### ISSUE TITLE
Feature Request - Threat/Aggro colors for when solo

### ISSUE THREAD

**Issue by Herdrage** [Tercioo/Plater-Nameplates#34]
I think it would be good if there was an option to choose a nameplate (and or border/name) color for when you have aggro but aren't in a group with a tank. Because I think "aggro on you" option for DPS in a raid/dungeon should be a color you don't see often to really warn you, which with how it is now it uses the same colors you see if you have aggro as dps in the open world. Another reason is that I like having a single nameplate color define what good is across all roles, so if I'm a tank and have good threat then the nameplate would be red, and if I'm dps in a raid with no threat then the nameplate would also be red in that situation. Sorry if I'm not explaining it well. I think elvui does it like that and it's just something I got used to.

**Comment by cont1nuity** [comment]
I understand. So just an option to always use the "no aggro" color while solo or an additional color setting + that option?

**Comment by cont1nuity** [comment]
Probably will implement a "solo" color for DPS and an option to toggle usage.

**Comment by cont1nuity** [comment]
Implemented with pull request #42. Will show up in the next release.

**Comment by cont1nuity** [comment]
Published in v8.2.0.277. Issue can be closed.
