### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Erdrian** [Tercioo/Plater-Nameplates#53]
**Game and Plater version**
Game：8.2.5.32750
Plater: 8.2.5.281

**Describe the bug**

    

- when i switch to druid feral, the skill range monitoring will be permanently effective, no matter whether the monster is in the skill range or not, the transparency will be reduced.

- Non-configuration reasons, it happend as well as the default configuration,

- This is not a problem with switching spec, or with leopard morphologies that are not specialized in the feral

**Screenshots**
![Snipaste_2019-12-16_12-30-31](https://user-images.githubusercontent.com/58811190/70885363-a270f280-2013-11ea-9778-c8025537e522.png)
![Snipaste_2019-12-16_12-31-09](https://user-images.githubusercontent.com/58811190/70885369-a69d1000-2013-11ea-96c7-655689e369f6.png)
![Snipaste_2019-12-16_12-33-45](https://user-images.githubusercontent.com/58811190/70885378-a8ff6a00-2013-11ea-8811-0d82b13ac2ca.png)

**Comment by cont1nuity** [comment]
The talent [Lunar Inspiration] (lvl 15, 3rd) alters Moonfire spellID, which seems to result in the range check not using the correct spell.
I will verify this.

**Comment by cont1nuity** [comment]
Range checks switched to distance instead of spells with SL.
