### ISSUE TITLE
Enhancement Request - Allow for Cast Bar Y Offset on Friendly NPC/Player

### ISSUE THREAD

**Issue by zA8a82K** [Tercioo/Plater-Nameplates#56]
**Game and Plater version**
Plater 8.3.0.286, WOW 8.3.0 (33115)

**Description**
I want move the cast bars down, but I see the Y Offset is only available for Enemy plates. The result is I've offset enemy cast bars, but friendly bars are in the wrong spot and display on top of the nameplate.

My suggestion is either include the Cast Bar Y Offset on Friendly Npc / Player configuration sections or add Cast Bar Y Offset as a global setting in Advanced tab.

**Screenshots**
This is how my frames look for Enemy cast bars:
![offset](https://user-images.githubusercontent.com/60550298/73596289-bcf62100-4518-11ea-80ee-1bfa42201855.png)

In contrast all friendly players and NPCs don't have the offset, which results in the nameplate text being covered:
![default](https://user-images.githubusercontent.com/60550298/73596314-e020d080-4518-11ea-9cb9-c3df21e39898.png)

**Other Information**
I'm assuming the castbars can be moved via Modding, but I don't have knowledge of LUA and thought this enhancement would be helpful for any users with friendly cast bars enabled.

Thank you

**Comment by cont1nuity** [comment]
This is implemented with the latest alpha.
