### ISSUE TITLE
Level/Strata

### ISSUE THREAD

**Issue by vandiel01** [Tercioo/Plater-Nameplates#58]
Separate Bodyguard to Target Scaling

The target of any mobs are good to what I set, but follower (in Nazj).. ike! soo big cuz literally following me everywhere

![image](https://user-images.githubusercontent.com/52209920/77829229-b76b2080-70ee-11ea-9a97-596ec9ed36e0.png)
![image](https://user-images.githubusercontent.com/52209920/77829241-c9e55a00-70ee-11ea-90ec-981141405f7d.png)

**Comment by cont1nuity** [comment]
A fine-tune scale of 1.44 is a tad much, actually. Usual values are <1 to counter scaling issues. You should increase the general sizes for everything (bars, icons, texts, etc.) and reduce the scaling.

As an example with Fine Tune Scale 1:
![image](https://user-images.githubusercontent.com/10164755/77854834-e8317f80-71ec-11ea-8c74-cf5b206096f3.png)

I'll add some options to move / scale these in the near future.

**Comment by cont1nuity** [comment]
Latest alpha version (which should be up on twitch soon) has some options for positioning and scaling on the advanced tab.
