### ISSUE TITLE
Improvement: TullaCC Support

### ISSUE THREAD

**Issue by DjRicko** [Tercioo/Plater-Nameplates#59]
Plater already has an option to disable cooldown count on auras from OmniCC, there's a cpu lightweight version of OmniCC, made by the same author, where the option however doesn't work, named TullaCC.
https://github.com/tullamods/tullaCC/issues/19
By changing the way the OmniCC disable works to just set that value, it should work for both addons, instead of the more complicated way it does it now, with adding themes and stuff to OmniCC?

**Comment by cont1nuity** [comment]
I will have a look into this. Especially regarding the following statement: "cooldown.noCooldownCount = true, which both OmniCC and tullaCC obey."

**Comment by cont1nuity** [comment]
Latest Plater alpha (which should show up soon on twitch/curseforge) should support tullaCC.
