### ISSUE TITLE
Nameplates BUG

### ISSUE THREAD

**Issue by Faust911** [Tercioo/Plater-Nameplates#60]
**Game and Plater version**
8.3.7,Plater-v8.3.0.305-Retail

**Describe the bug**
- Nameplates in plater doesn t appear

- When the bug started (a date, wow path release, details update, etc)?
The bug started 11.08.2020, reinstalling  doesn't help, pressing "ctrl+v" or etc doesn't help also
- Additional information:

**Lua Error**
Message: ...\Details\Libs\DF\Details-Framework-Classic\panel.lua:8105: attempt to call upvalue 'ChannelInfo' (a nil value)
Time: Tue Aug 11 15:48:23 2020
Count: 142
Stack: ...\Details\Libs\DF\Details-Framework-Classic\panel.lua:8105: attempt to call upvalue 'ChannelInfo' (a nil value)
[string "@Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua"]:8105: in function `PLAYER_ENTERING_WORLD'
[string "@Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua"]:7927: in function <...\Details\Libs\DF\Details-Framework-Classic\panel.lua:7921>
[string "=[C]"]: in function `OnEvent'
[string "@Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua"]:7825: in function `SetUnit'
[string "@Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua"]:8840: in function `SetUnit'
[string "@Interface\AddOns\Plater\Plater.lua"]:2807: in function `func'
[string "@Interface\AddOns\Plater\Plater.lua"]:3147: in function <Interface\AddOns\Plater\Plater.lua:3144>

Locals: self = NamePlate11PlaterUnitFrameCastBar {
 0 = <userdata>
 OnTick_Channeling = <function> defined @Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua:7988
 OnTick = <function> defined =[C]:-1
 isNamePlate = true
 UpdateInterruptState = <function> defined @Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua:7736
 UNIT_SPELLCAST_CHANNEL_START = <function> defined @Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua:8190
 ScheduleToHide = <function> defined @Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua:7869
 IsProtected = <function> defined @Interface\AddOns\Plater\Plater.lua:9834
 SetUnit = <function> defined @Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua:7782
 Animation_StopAllAnimations = <function> defined @Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua:8090
 OnShow = <function> defined @Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua:7897
 SetHook = <function> defined @Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\fw.lua:2202
 barTexture = <unnamed> {
 }
 UNIT_SPELLCAST_CHANNEL_UPDATE = <function> defined @Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua:8368
 Animation_FadeIn = <function> defined @Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua:8072
 flashTexture = <unnamed> {
 }
 fadeOutAnimation = <unnamed> {
 }
 extraBackground = <unnamed> {
 }
 OnHideWidget = <function> defined @Interface\AddOns\Plater\Plater.lua:9758
 HasScheduledHide = <function> defined @Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua:7858
 HookList = <table> {
 }
 unit = "nameplate25"
 UNIT_SPELLCAST_DELAYED = <function> defined @Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua:8351
 flashAnimation = <unnamed> {
 }
 Animation_FadeOut = <function> defined @Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua:8060
 WidgetType = "castBar"
 Icon = <unnamed> {
 }
 SetDefaultColor = <function> defined @Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua:7682
 IsValid = <function> defined @Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua:7716
 lazyUpdateCooldown = 0.100000
 RunHooksForWidget = <function> defined @Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\fw.lua:2184
 DoScheduledHide = <function> defined @Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua:7845
 ScriptRunNoAttach = <function> defined @Interface\AddOns\Plater\Plater.lua:9749
 Animation_FadeInFinished = <function> defined @Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua:8053
 percentText = <unnamed> {
 }
 PlateFrame = NamePlate11 {
 }
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua:8104
 GetTexture = <function> defined @Interface\AddOns\Details\Libs\DF\Details-Framework-Classic\panel.lua:6883

**Screenshots**
![image](https://user-images.githubusercontent.com/69514030/89899121-7a5d8180-dbea-11ea-826f-2ea691571380.png)

**Other Information**
If necessary, add more info here.

**Comment by cont1nuity** [comment]
You have a classic Details version installed. Bring that back to retail.
**_Details\Libs\DF\Details-Framework-Classic_**

Thank twitch for the mess.
