### ISSUE TITLE
SLBeta 271x SharedXML\FrameUtil.lua:57: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: <unnamed>:GetScaledRect().

### ISSUE THREAD

**Issue by Italist** [Tercioo/Plater-Nameplates#61]
beta 90001

Plater-v9.0.1.11-Beta

**Describe the bug**
just questing

**Lua Error**
271x SharedXML\FrameUtil.lua:57: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: <unnamed>:GetScaledRect().
[string "=[C]"]: in function `GetScaledRect'
[string "@SharedXML\FrameUtil.lua"]:57: in function `GetUnscaledFrameRect'
[string "@SharedXML\LayoutFrame.lua"]:288: in function <SharedXML\LayoutFrame.lua:287>
[string "@SharedXML\LayoutFrame.lua"]:325: in function `Layout'
[string "@SharedXML\LayoutFrame.lua"]:33: in function <SharedXML\LayoutFrame.lua:32>
[string "=[C]"]: in function `Show'
[string "@Plater\Plater-Plater-v9.0.1.11-Beta.lua"]:3025: in function `func'
[string "@Plater\Plater-Plater-v9.0.1.11-Beta.lua"]:3407: in function <Plater\Plater.lua:3404>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
 OnLeave = <function> defined @Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua:72
 OutAnimFinished = <function> defined @Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua:124
 widgetTag = ""
 GetWidgetWidth = <function> defined @Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua:113
 widgetType = 13
 Spell = <unnamed> {
 }
 GetWidgetHeight = <function> defined @Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua:117
 SetTooltipOwner = <function> defined @Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua:31
 Setup = <function> defined @Blizzard_UIWidgets\Blizzard_UIWidgetTemplateSpellDisplay.lua:12
 SetFontStringColor = <function> defined @Blizzard_UIWidgets\Blizzard_UIWidgetTemplateSpellDisplay.lua:30
 hasTimer = false
 widgetID = 2864
 InAnimFinished = <function> defined @Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua:121
 widgetContainer = <unnamed> {
 }
 FadeInAnim = <unnamed> {
 }
 SetFontColor = <function> defined @Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua:94
 AnimIn = <function> defined @Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua:146
 widgetSetID = 444
 layoutDirection = 0
 tooltipAnchor = "ANCHOR_BOTTOMLEFT"
 ResetAnimState = <function> defined @Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua:140
 outAnimType = 0
 OnLoad = <function> defined @Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua:109
 OnReset = <function> defined @Blizzard_UIWidgets\Blizzard_UIWidgetTemplateSpellDisplay.lua:25
 GetOutAnim = <function> defined @Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua:134
 GetInAnim = <function> defined @Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua:128
 FadeOutAnim = <unnamed> {
 }
 OnEnter = <function> defined @Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua:35
 SetTooltip = <function> defined @Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua:17
 inAnimType = 0
 SetEnabledState = <function> defined @Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua:102
 orderIndex = 1
 AnimOut = <function> defined @Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua:162
 SetMouse = <function> defined @Blizzard_UIWidgets\Blizzard_UIWidgetTemplateBase.lua:3
}

**Comment by shane-ley** [comment]
I've had the same error appear while doing the quest Pool of Potions in the House of Plagues. First time it appeared by just being in the area of the potion pools; however, after a reload it only appeared after tagging an ooze near the pools. Hope this helps.
