### ISSUE TITLE
SL Beta [ADDON_ACTION_BLOCKED] AddOn 'Plater' tried to call the protected function 'SetTargetClampingInsets()'.

### ISSUE THREAD

**Issue by Italist** [Tercioo/Plater-Nameplates#62]
**Game and Plater version**
beta 90001
Plater-v9.0.1.11-Beta

**Describe the bug**
just questing, lua error

**Lua Error**
1x [ADDON_ACTION_BLOCKED] AddOn 'Plater' tried to call the protected function 'SetTargetClampingInsets()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetTargetClampingInsets'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:305: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:244>
[string "=[C]"]: in function `SetupClassNameplateBars'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:119: in function `OnNamePlateAdded'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:47>

**Comment by cont1nuity** [comment]
Using as #74 as collective issue for this kind of widget errors.
