### ISSUE TITLE
Error after login displayed

### ISSUE THREAD

**Issue by FelixReuthlinger** [Tercioo/Plater-Nameplates#64]
For quite some time now I got this error when logging in with any char and having Plater (latest version) installed and acitve:

Message: Interface\AddOns\Plater\Plater-Plater-1.13.5.91-Classic.lua:8031: attempt to call method 'RemoveRule' (a nil value)
Time: Mon Oct 12 08:23:13 2020
Count: 1
Stack: Interface\AddOns\Plater\Plater-Plater-1.13.5.91-Classic.lua:8031: attempt to call method 'RemoveRule' (a nil value)

Locals: 

I though maybe this gonna be resolved some time, but maybe noone being aware about this?

**Comment by cont1nuity** [comment]
Please check your Masque installation. Sounds to me like you're using an outdated version.

**Comment by FelixReuthlinger** [comment]
Ok, thx. Opened one in the other repo, will close this here.
But afaik it is not related to not using the latest version, I always update via Twitch and Weakauras companion app.
