### ISSUE TITLE
Protection warriors can execute in Shadowlands

### ISSUE THREAD

**Issue by rhynolm** [Tercioo/Plater-Nameplates#65]
Options tooltip:
"Show and indicator when the unit is in execute range... Warrior: Arms and Fury Spec"

Protection now has execute.  Can we adjust the options filter so protection automatically has execute indicator?

**Comment by cont1nuity** [comment]
Will be in one of the next versions.

**Comment by cont1nuity** [comment]
Newest version added execute for all specs.
