### ISSUE TITLE
In combat doesnt work against training dummies

### ISSUE THREAD

**Issue by Jaden-Giordano** [Tercioo/Plater-Nameplates#66]
**Game and Plater version**
Plater: 9.0.1.309-retail
WoW: 9.0.1

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
Set in combat healthbar size different from out of combat.

- Result (what happens when you follow the steps above):
When entering combat with a training dummy, the nameplate state does not change.

- Expected (what you think the expected behavior would be when following the steps:
Healthbar should be using in combat sizing/profile settings.

- When the bug started (a date, wow path release, details update, etc)?
After 9.0.1.307-retail update (happened with this https://github.com/Tercioo/Plater-Nameplates/commit/67d3a27332ad262917e9c5551c503bf88307ed47#diff-1db561366533fc606b39c5b02911293cbfd0ef25cb949792a0ff1f2ea1df9887R11).

- Additional information:
This works for units who can change their state to in combat but since training dummies are never in combat this doesn't work. I primarily use training dummies to test my profile settings. I have a fork (https://github.com/Jaden-Giordano/Plater-Nameplates/tree/jg/global-combat-toggle) currently that adds a checkbox to the general settings to toggle this new logic, but I see there y'all have been changes to try to fix (https://github.com/Tercioo/Plater-Nameplates/commit/4951f09a280c918e716d14b6b2951715a8acbbd3). If you want to take a look at my work and let me know if its something I should make a PR with.

**Screenshots**
Settings:
![image](https://user-images.githubusercontent.com/5057468/96187386-c29e6600-0ef1-11eb-91c0-40f9019bc88c.png)

Out of combat:
![image](https://user-images.githubusercontent.com/5057468/96187398-c9c57400-0ef1-11eb-8ead-9eb04cb86ec3.png)

In combat:
![image](https://user-images.githubusercontent.com/5057468/96187418-d21daf00-0ef1-11eb-9835-6bad848976b4.png)

**Comment by cont1nuity** [comment]
Training dummies do not have a combat state, they are always out of combat.
Plater checks the combat state of the unit, not the player.
This is expected behavior until blizzard decides that dummies will be in combat as well.

**Comment by Jaden-Giordano** [comment]
Can we add a setting to disable this for testing purposes? I have a fork with that option being added. Should I just open a PR?
