### ISSUE TITLE
Anti-contribution?

### ISSUE THREAD

**Issue by Jaden-Giordano** [Tercioo/Plater-Nameplates#68]
Hey I wanted to bring this to light @Tercioo. I recently opened up an issue regarding the new combat logic that was added to Plater in the new shadowlands update (issue for reference #66). That issue was closed rather rapidly before the issue was actually resolved (now I already had a fork where I did the research to see where the issue occurred and a quick patch), With it being closed with and not being solved I decided to open a PR with my work (PR for reference #67). That work was rough and I had a couple questions on getting it to load correctly in WoW so it needed a bit of polish, but the PR was closed right away because it wasn't in the right place in the menu, and there were a few code styling changes needed I guess. The problem comes with this commit [c1281e1](https://github.com/Tercioo/Plater-Nameplates/commit/c1281e1de4a980732449eac0f28bf173b86bef14), the implementation is the exact same implementation I did with a few code changes. So rather than making the changes to my PR and merging with actual credit to my work, it was just copied and cleaned up. I noticed the details repo is actually managed like a proper open source project cuz its more widely used, but the gatekeeping happening by the maintainer of this project is kinda sickening, because it seems to have happened before by another person who wanted to contribute (#57).

I just really enjoy using Plater and wanted to make a contribution because its open source but it seems like the maintainer of this just wants all the credit for anything done. It's very anti open-source and kind of sad to see.

**Comment by cont1nuity** [comment]
I am not against any contribution. In this case it was a change which was done for the SL alpha and, as you noticed, unfinished. In an pre-patch time where everyone is complaining about changed behavior and bugs, I'd rather fix it myself than waiting on feedback loops.
Having feature PRs is more than welcome if the changes are a) close to something working (which was the case, missed only the cast bars check), b) are useful contributions and match the rest of Plater (yep) and c) are not something already being worked on and/or change bugged behavior while the PR is a feature request and not a fix for the overall issue.

It is not about credit for me. I honestly don't care as long as the result is a working Plater and I can easily add you in the next release notes for that point.
It is about the bugs I still had in the code from alpha which I was working on already. as you can see in the commit, that needed a bit more changes.
This was just the easier way. Outside of pre-patch weeks I would have had the time to work on PRs.
