### ISSUE TITLE
Plater / Details error adjusting skins and text fonts/color

### ISSUE THREAD

**Issue by ala75** [Tercioo/Plater-Nameplates#69]
**Game and Plater version**
Plater version: v9.0.1.309-retail
Game version v9.0.1

**Game and Details! version**
Details! version: R7908
Game version v9.0.1

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):

First thanks for the great addon and all the efforts of the team.

I made my UI from scratch for the pre-patch. Problems with details started setting it up with plater nameplates enabled (configured that addon first).

I have 2 errors which i have posted also on the details GIT as issues #122 and #123. Error posted here is identical as issue #123 on the Details GIT

Error is being produced while configuring Details!:
Error starts when choosing different skin for bars and changing the font color in for example the title bar menu in Details!. Same thing happends when adjusting in the Statusbar menu: adjusting Color and transparancy, editing text color in the micro displays (cogwheel). When set the text color to white (255,255,255) the bar turn green and errors start popping up related to plater and details.

Even after disabeling details the error will still popup for plater. Before the installation of details there was no error with plater. I have to put a backup from WTF back (from before details installation) to stop the plater error.

- Expected (what you think the expected behavior would be when following the steps):

- When the bug started (a date, wow path release, details update, etc)?

Fresh wow retail installation (pre-patch) with elvui, plater and details. Addons are all up to date.

- Additional information:

I will post my details and Plater config file from WTF at the bottem

**Lua Error**

1x Plater\Plater-Plater-v9.0.1.309-Retail.lua:8586: attempt to index local 'platerRules' (a boolean value)
[string "@Plater\Plater-Plater-v9.0.1.309-Retail.lua"]:8586: in function <Plater\Plater.lua:8552>

Locals:
fromInit = nil
platerThemeName = "Plater Nameplates Theme"
platerRuleName = "Plater Nameplates Rule"
platerTheme = <table> {
 textStyles = <table> {
 }
 fontFace = "Fonts\FRIZQT__.TTF"
 timerOffset = 0
 drawSwipes = true
 scaleText = true
 tenthsDuration = 0
 fontOutline = "OUTLINE"
 minSize = 0.500000
 mmSSDuration = 0
 enableText = true
 effect = "pulse"
 yOff = 0
 xOff = 0
 fontSize = 18
 fontShadow = <table> {
 }
 minEffectDuration = 30
 minDuration = 2
 anchor = "CENTER"
}
platerRules = false
(*temporary) = <function> defined @Details\Libs\DF\fw.lua:286
(*temporary) = <table> {
 4 = <table> {
 }
}
(*temporary) = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to index local 'platerRules' (a boolean value)"
DF = <table> {
 CooldownToClass = <table> {
 }
 ClassCache = <table> {
 }
 SavePositionOnScreen = <function> defined @Details\Libs\DF\panel.lua:2137
 CreateTabContainer = <function> defined @Details\Libs\DF\panel.lua:3898
 IsUnitTapDenied = <function> defined @Details\Libs\DF\fw.lua:3982
 CancelTimer = <function> defined @ArkInventory\Externals\Ace3\AceTimer\AceTimer-3.0.lua:147
 NewLabel = <function> defined @Details\Libs\DF\label.lua:275
 BuildStatusbarAuthorInfo = <function> defined @Details\Libs\DF\panel.lua:6943
 PanelCounter = 338783
 IconPick = <function> defined @Details\Libs\DF\panel.lua:1515
 debug = false
 LabelNameCounter = 338940
 GetCurrentSpec = <function> defined @Details\Libs\DF\fw.lua:3303
 alias_text_colors = <table> {
 }
 HidaAllBarrasInfo = <function> defined @Details\frames\window_playerbreakdown.lua:420
 UnitFrameFunctions = <table> {
 }
 ScheduleTimer = <function> defined @ArkInventory\Externals\Ace3\AceTimer\AceTimer-3.0.lua:94
 CreateCastBar = <function> defined @Details\Libs\DF\panel.lua:8541
 RegisterScriptComm = <function> defined @Details\Libs\DF\fw.lua:3924
 ShowPanicWarning = <function> defined @Details\Libs\DF\panel.lua:1908
 UnitGroupRolesAssigned = <function> defined @Details\Libs\DF\fw.lua:58
 SetAutoCompleteWithSpells = <function> defined @Details\Libs\DF\auras.lua:1061
 ShowTutorialAlertFrame = <function> defined @Details\Libs\DF\fw.lua:1886
 CooldownsExternals = <table> {
 }
 GetSpecializationRole = <function> defined @Details\Libs\DF\fw.lua:94
 SpecListByClass = <table> {
 }
 FRAMELEVEL_BACKGROUND = 150
 CreateHealthBar = <function> defined @Details\Libs\DF\panel.lua:7400
 RunHooksForWidget = <function> defined @Details\Libs\DF\fw.lua:2275
 GetDefaultColorList = <function> defined @Details\Libs\DF\colors.lua:170
 button_templates = <table> {
 }
 CreateNewDropdownFrame = <function> defined @Details\Libs\DF\dropdown.lua:1137
 ReskinSlider = <function> defined @Details\Libs\DF\fw.lua:3162
 CriaNovaBarraInfo2 = <function> defined @Details\frames\window_playerbreakdown.lua:5771
 ColorPick = <function> defined @Details\Libs\DF\panel.lua:1491
 CreateSwitch = <function> defined @Details\Libs\DF\slider.lua:967
 font_templates = <table> {
 }
 embeds = <table> {
 }
 SetAnchor = <function> defined @Details\Libs\DF\fw.lua:829
 trim = <function> defined @Details\Libs\DF\fw.lua:597
 NewSplitBar = <function> defined @Details\Libs\DF\split_bar.lua:590
 GetSpecListFromClass = <function> defined @Details\Libs\DF\fw.lua:3757
 FindClassForCooldown = <function> defined @Details\Libs\DF\spells.lua:883
 FindHighestParent = <function> defined @Details\Libs\DF\panel.lua:3792
 BuildDropDownFontList = <function> defined @Details\Libs\DF\dropdown.lua:903
 HasHook = <function> defined @Details\Libs\DF\fw

**Other Information: Details and Plater WTF settings file from saved variables**

Details: https://pastebin.com/wSiiHj4Y
Plater: had to split the file due to size restrictions of pastbin:
plater WTF saved variable part 1 line 1-7504: https://pastebin.com/u1vUkSYV
plater WTF saved variable part 2 line 7505-end: https://pastebin.com/zhyjbKMY

**Comment by ala75** [comment]
https://postimg.cc/CBx813T7

**Comment by cont1nuity** [comment]
It appears that OmniCC is still broken. Can you access your OmniCC options? Shows a blank page and resetting OmniCC options through deleting the SavedVariable OmniCC.lua seems to fix this.
The error seems to be closely related, I never experienced this, though.

**Comment by ala75** [comment]
Thank you for your quick response.  Appears you are spot on! I could trigger the error again by just updating Details! to the latest release build. Even after disabeling Details! the error would persist on a reload/relog. I did some testing with a (working) backup of my settings (interface/WTF) to test what you suggested. When the error triggers i can still open OmniCC options. No visual abnormalities like a blank screen. What I did notice:  Normaly there are 2 entries in the Theme section; Default and Plater Nameplates Themes. After a few seconds the Default dissapears and only the Plater nameplates Theme is shown. Did logout, deleted the omnicc Variables and logged back in. The error is not showing now. Did a couple of reloads and logouts and it seems to be temporarely solved.

This is the most weird interaction i have seen for a while between 3 addons. I never suspected something with OmniCC. Do you have a suggestion what to do next? Should I issue this on the OmniCC Git? Many thanks for you time and efforts

**Comment by cont1nuity** [comment]
I cannot reproduce the issue with the broken options any longer, have you checked for updates of OmniCC?

**Comment by ala75** [comment]
i switched back to stock blizzard cooldown timers and the timers in the plater options. I will test again tomorrow with OmniCC again (birthday today :P)

**Comment by ala75** [comment]
Hi there, 

Only had an hour to test it with OmniCC installed. I havent seen the error yet. Hardest thing (for all of us i guess) is to reproduce errors consistently. An hour of testing is not too much. I know that if Details! addon is updated it reproduces this error consistently. Unfortunately i don't have any pending update for it, have to wait on an Details! addon update to know for sure. My feeling for now is good though. 

Main reason i had so little test time yet is that I found 2 other errors (bugs?) which i can reproduce 100% (that took most of my playtime) . One is with Details!, the other one Plater. I will post them on GIT later after work with steps/info and screenshots on how to reproduce them

**Comment by cont1nuity** [comment]
Thanks for the feedback. If the error does not occur anymore, I'd close the ticket.

**Comment by ala75** [comment]
Yeah I agree close the ticket. For now it looks resolved. Thanks for the continuing support, much appreciated :)
