### ISSUE TITLE
Plater error on clicking dialogue option NPC

### ISSUE THREAD

**Issue by ala75** [Tercioo/Plater-Nameplates#70]
**Game and Plater version**
Plater version: v9.0.1.309-retail
Plater version: Plater-v9.0.1.310-Retail-5-g1c12fed-alpha
Game version v9.0.1.36272

**Describe the bug**
- Was cleaning up a quest in Stormwind City. I still had the quest "To be Prepared" open in the Stormwind Docks. This quest starts the BFA intro which you can skip if you did it on a another character. The quest remains then.  

step 1: Talk to recruiter Lee to accept the quest (quest requires 4 steps)
step 2: click 3 items (a,b,c): 

a) Armor polished
b) Weapon empowered
c) Last meal eaten
d) Warmed up with a duel is

Step 3: step d) Warmed up with a duel requires You to talk to one of the NPC's to duel them. The moment You click the dialogue option  "Let's duel" the error triggers.

_ps. Don't kill the npc otherwise you cant reproduce it anymore_

- Additional information:

Just in case: OmniCC/TullaCC removed due to earlier bug findings

Tested with latest release version and latest alpha version of plater 

**Lua Error**

2x Plater\Plater-Plater-v9.0.1.310-Retail.lua:5726: bad argument #1 to 'unpack' (table expected, got nil)
[string "=[C]"]: ?
[string "@Plater\Plater-Plater-v9.0.1.310-Retail.lua"]:5726: in function `SetQuestColorByReaction'
[string "@Plater\Plater-Plater-v9.0.1.310-Retail.lua"]:5753: in function `ColorOverrider'
[string "@Plater\Plater-Plater-v9.0.1.310-Retail.lua"]:5820: in function `FindAndSetNameplateColor'
[string "@Plater\Plater-Plater-v9.0.1.310-Retail.lua"]:3203: in function `func'
[string "@Plater\Plater-Plater-v9.0.1.310-Retail.lua"]:3450: in function `EventHandler'
[string "@Plater\Plater-Plater-v9.0.1.310-Retail.lua"]:3460: in function `RunFunctionForEvent'
[string "@Plater\Plater-Plater-v9.0.1.310-Retail.lua"]:1376: in function <Plater\Plater.lua:1356>
[string "@SharedXML\C_TimerAugment.lua"]:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"

**Screenshots**
Screenshot with different steps
https://postimg.cc/mPBYqBkj

**Comment by cont1nuity** [comment]
Fixed in latest alpha via 47dbfd2

**Comment by cont1nuity** [comment]
Thanks for the detailed report!

**Comment by ala75** [comment]
Confirmed that it's fixed the latest alpha build. Thanks you :)
