### ISSUE TITLE
Personal Nameplate Anchoring

### ISSUE THREAD

**Issue by Effeh** [Tercioo/Plater-Nameplates#71]
**Game and Plater version**
Plater-v9.0.1.310-Retail
Game 9.0.1.36322

**Describe the bug**
Frames anchored to the personal nameplate using WA2 and Plater shift on the Y axis sometimes on zone transition (and other events) and remain so until /reload (Or sometimes stubbornly until entire game reload). This happens with Plater, but never Kuinameplates - can't speak for other addons.
I think this is also what was taking place in this issue: https://github.com/Tercioo/Plater-Nameplates/issues/26

I believe it's the frame WeakAurasAttachToPRD that's the culprit, but it only happens with the Plater personal nameplate.

**Screenshots**
Here's how my personal resource display looks upon login:
![uponlogin](https://user-images.githubusercontent.com/73201826/96687601-2095d800-134e-11eb-890b-5b9bb6c13b88.png)

And this is what happens sometimes after hearthing, dying, or just progressing through a dungeon (randomly):
![afterawhile](https://user-images.githubusercontent.com/73201826/96687711-458a4b00-134e-11eb-81c3-2b5b7a4dc0f0.png)

When I /fstack, the WeakAurasAttachToPRD frame normally aligns to the top of the Plater PRD:
![fstackaligned](https://user-images.githubusercontent.com/73201826/96690465-b97a2280-1351-11eb-8ca9-e56445017873.png)

When the problem occurs, it winds up in the middle, and all attached objects drift accordingly:
![fstackmisaligned](https://user-images.githubusercontent.com/73201826/96690654-f47c5600-1351-11eb-9736-34d72a844ae5.png)

**Other Information**
My knowledge of lua is very poor, but my very uneducated guess is that this may be mostly the fault of WA2. There appears to be code regarding the PRD in Weakauras.lua that factors in Kui and Elvui nameplates but not Plater, perhaps leading to this behaviour. 

However, these other nameplate addons also include their own invisible PRD anchor frame so that WA's anchor frame can be circumvented if needed. It would be greatly appreciated if such functionality was added to Plater so that the (likely) problematic WA2 code could be avoided completely.

Such as: https://github.com/kesava-wow/kuinameplates2/blob/master/Kui_Nameplates/plugins/personal-anchor.lua

**Comment by cont1nuity** [comment]
Adressed through https://github.com/WeakAuras/WeakAuras2/pull/2614

**Comment by cont1nuity** [comment]
PR has been closed. Next release of WA resolves this issue.
