### ISSUE TITLE
Release not working with WowUp and Cursebreaker

### ISSUE THREAD

**Issue by Pihlqvist** [Tercioo/Plater-Nameplates#72]
Any possibility of creating a tagged release that apps like [WowUp](https://wowup.io/guide/section/get-addons/install-from-url) and [CurseBreaker](https://github.com/AcidWeb/CurseBreaker) can use?

**Comment by cont1nuity** [comment]
Currently not planned.
Might look into it when we have the time on our hands.

**Comment by cont1nuity** [comment]
CurseBreaker (and probably WowUp) should work with the latest tagged releases.
