### ISSUE TITLE
Aura timer font settings not being respected

### ISSUE THREAD

**Issue by rwinders** [Tercioo/Plater-Nameplates#73]
**Game and Plater version**
Retail Plater-v9.0.1.316-Retail

**Describe the bug**
At some point while playing, my font settings for aura timer stop being respected (Expressway, size 10, centrally placed). Some of my auras display the wrong font, size, border, placement, etc. This seems to happen most consistently during group content. If I reload my UI, it goes back to normal.
- Actual:
![broken fonts](https://user-images.githubusercontent.com/6710842/100285646-1a36e500-2f26-11eb-9256-aedd934cfe2f.png)
- Expected:
![expected](https://user-images.githubusercontent.com/6710842/100285661-20c55c80-2f26-11eb-8044-ba606bb614ec.png)
- Settings:
![settings](https://user-images.githubusercontent.com/6710842/100285671-24f17a00-2f26-11eb-8ecd-d0f945014e81.jpg)
- When the bug started (a date, wow path release, details update, etc)?
Since I started using Plater at the end of BFA

**Comment by cont1nuity** [comment]
You can try this mod to see if it fixes the issue: https://wago.io/gSQ9tPyO7

**Comment by cont1nuity** [comment]
Seems to be around since the beginning... The same scale animation system is used here.
https://authors.curseforge.com/forums/world-of-warcraft/general-chat/lua-code-discussion/225834-scale-animations-bugging-fontstrings

**Comment by rwinders** [comment]
@cont1nuity That mod seems to have fixed the issue for me. Thanks!

**Comment by cont1nuity** [comment]
The latest alpha version should fix the issue without the mod as well.
