### ISSUE TITLE
Error during "Tea Tales" quest and world quests

### ISSUE THREAD

**Issue by RhapsodySL** [Tercioo/Plater-Nameplates#74]
**Game and Plater version**
Which is the game version and Plater version you're using.

**Plater**: Plater-v9.0.1.321-Retail
**WoW**: 9.0.2

**Describe the bug**

The following error message is spammed when controlling a unit in the "Tea Tales" world quest in Revendreth. This error also occurs during a similar quest in the main campaign.

As far as I can tell this occurs when in combat and once upon exiting combat, but I've seen it occur while moving around before without being in combat at all. Functionally speaking this doesn't appear to affect gameplay at all.

**Lua Error**

https://pastebin.com/vLhUaG5p

**Comment by cont1nuity** [comment]
I cannot reproduce this issue at all, unfortunately.
Please export your profile to wago.io and link it here.
In addition, please try to reproduce the issue with only Plater enabled.

**Comment by Caerdon** [comment]
I've been seeing this issue a lot as well.  It goes away when I disable Plater.

**Comment by Caerdon** [comment]
Another common place it occurs is at the cauldron world quest in Maldraxxus (where everyone throws the colored slimes in).

**Comment by cont1nuity** [comment]
This has become a know issue and there is still no fix available. There are several errors regarding widgets which originate in blizzard core code. Other nameplate addons have the same issues as well and it is currently unknown how to resolve this.

**Comment by Caerdon** [comment]
Looks like ElvUI was seeing it, and the dev says they fixed it (https://git.tukui.org/elvui/elvui/-/issues/2249).  They don't indicate the precise fix, but it seems like it might be hovering around here: https://git.tukui.org/elvui/elvui/-/commit/23088d428389d6e207e44f335a8dc044a84c4e2a

**Comment by cont1nuity** [comment]
I am monitoring that issue and it was reopened already. I have my doubts about that commit, but I'll give that a try.
