### ISSUE TITLE
Special characters bug

### ISSUE THREAD

**Issue by OlivierFerriot** [Tercioo/Plater-Nameplates#75]
When the name a a player has special char in it with at least another char after it, the special char is correctly shown (font ok with it)  but after that there is another char displayed as an error, but this char doesn't exist.
Example :
Sámu is shown Sá?mu
with the ? shown either as a rectangle or a diamond.
![PlaterBug](https://user-images.githubusercontent.com/6054349/101959014-cc4bfd80-3c04-11eb-83b3-1cc161ff8d29.png)

I tried 12 different fonts, all the time the same result.
In the screenshot it is the same font in the UnitFrame up top and in Plater.

**Comment by cont1nuity** [comment]
Export your profile to wago.io please and link it here.

**Comment by OlivierFerriot** [comment]
https://wago.io/MvHbNm7pr

**Comment by cont1nuity** [comment]
Try disabling the following mods:
- ".SL M+ Short Names"
- "!RussianRenamer"

Having multiple different renaming mods will have one not working or lead to conflicts. Both mods are not well implemented either...
