### ISSUE TITLE
Feature Request: Allow API to set color alphas

### ISSUE THREAD

**Issue by attickdoor** [Tercioo/Plater-Nameplates#76]
I've hacked together a solution that seems to work for me, but I'm sure I've missed some intricacies and so don't want to PR yet. I'd like to request changing `Plater.SetNameplateColor (unitFrame, r, g, b)` to `Plater.SetNameplateColor (unitFrame, r, g, b, a)`, and similarly for any other API functions that allow for setting colors. This would involve updating `Plater.ChangeHealthBarColor_Internal` and probably a number of other functions in a small way. I don't think it would break the API for any existing mods, but I think it's a valuable feature to have.

**Comment by cont1nuity** [comment]
Let's see the PR :)

**Comment by attickdoor** [comment]
Done. #78
