### ISSUE TITLE
Plater modding update enhancment

### ISSUE THREAD

**Issue by Addonman** [Tercioo/Plater-Nameplates#77]
Would it be possiable when user updates plater  modding from wago.io that it leaves things  size ,position,color ,.. unchanged similar to weakaura addon?

**Comment by Tercioo** [comment]
It's a good question, are you using the options system?

------ Original Message ------

**Comment by Addonman** [comment]
Checked moddings i use and i guess not 1 author is using them.

**Comment by cont1nuity** [comment]
Well, some are. There are updated versions around for some of the more popular addons.
This is the way to go and keep settings while updating.
