### ISSUE TITLE
Add Withering Discharge to Big Alert list

### ISSUE THREAD

**Issue by Daluur** [Tercioo/Plater-Nameplates#88]
I think the spell [Withering Discharge](https://www.wowhead.com/spell=341969/withering-discharge) should be added to the list of Big Alert spells, it feel it is at least as important as most other spells in that list.

(I did add it myself, but I still think it should be baseline)

**Comment by Tercioo** [comment]
Could you provide a video of the mob using this spell?
Can be a random youtube video at the time mark where this mob is present 
and casting the spell.

------ Original Message ------

**Comment by Daluur** [comment]
In this video, the mob marked with skull starts casting it at around 26:31
https://youtu.be/Bc4V2pB7CMM?t=1588

I did realize after I made this issue that the spell is on the small alerts lists. I just have not noticed the small blink when I have been fighting them. I do still believe that the spell is important enough to be on the big alert list, also when compared to the rest of the spells in that area of the dungeon.
