### ISSUE TITLE
ConsolePort's raid cursor compatibility (taint issue)

### ISSUE THREAD

**Issue by RedSkotina** [Tercioo/Plater-Nameplates#89]
**Game and Plater version**
Wow 9.0.2 
Plater-v9.0.2.326b-Retail

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen)
1. Install and enable ConsolePort wow addon.
2. Bind raid cursor ('Target unit frames (hold)' or 'Toggle Raid Cursor')
3. Use button with the bind
4. Look at error window
- Result (what happens when you follow the steps above):
Error window and raid cursor is not enabled
- Expected (what you think the expected behavior would be when following the steps):
ConsolePort's Raid cursor is enabled without lua errors
- When the bug started (a date, wow path release, details update, etc)?
Dont know. First try raid cursor right now
- Additional information:
Error still happen with all disabled Plater's mods and scripts.
Error still happen with all disabled wow modification except ConsolePort and Plater.
Error is gone when i dont have any nameplates(include friendly) at screen after reload.
But Error happen after first Plater's nameplate  is created at screen.

**Lua Error**
```
Message: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: Interface\FrameXML\RestrictedInfrastructure.lua:259: Cannot insecurely modify restricted table
Time: Sat Feb 27 20:06:05 2021
Count: 1
Stack: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: Interface\FrameXML\RestrictedInfrastructure.lua:259: Cannot insecurely modify restricted table
[string "=[C]"]: ?
[string "@Interface\FrameXML\RestrictedExecution.lua"]:431: in function <Interface\FrameXML\RestrictedExecution.lua:420>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface\FrameXML\SecureHandlers.lua"]:285: in function <Interface\FrameXML\SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: (*temporary) = "Call failed: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: Interface\FrameXML\RestrictedExecution.lua:431: Call failed: Interface\FrameXML\RestrictedInfrastructure.lua:259: Cannot insecurely modify restricted table"

```

**Screenshots**
![image](https://user-images.githubusercontent.com/1965405/109394817-fc6c8800-7939-11eb-8f55-5f68fbb858a0.png)

**Other Information**

**Comment by cont1nuity** [comment]
As CP is trying to access frames (which ones exactly?), this does not fall into Platers category, but it would be up to CP to address this issue.
