### ISSUE TITLE
Target Bracket Indicator 'Pins' is scaled too high

### ISSUE THREAD

**Issue by Breakerzeus** [Tercioo/Plater-Nameplates#92]
**Game and Plater version**
WoW: 9.0.5
Plater: v9.0.2.327-Retail

**Describe the bug**
The Target Bracket Indicator 'Pins' is scaled way too high. The Pins look very strange to me and since you can't scale the indicator it's annoying, so that I rerolled to the previous version.
The other indicators look like fine to me.

**Lua Error**
no LUA errors

**Screenshots**
How it looks like since newest update:
https://imgur.com/a/j4oCByc

How it should look like IMHO:
https://imgur.com/a/XHYRcrm

**Other Information**

**Comment by cont1nuity** [comment]
Fixed in latest alpha.
