### ISSUE TITLE
Level & Strata issue

### ISSUE THREAD

**Issue by RinZJ** [Tercioo/Plater-Nameplates#93]
Hey, I have an issue when trying to use level and strata setting. Without using it the nameplates will overlap as you would expect with the entire nameplate either going behind or in front of the other.
However with custom level and strata enabled it kind of does a mix and some parts are behind some in front. For example in the first screenshot below you can see the nameplates sort of mesh together instead of one behind another. 

If there is any way to fix this that would be great or alternatively make it possible to use the fine tune scale setting without enabling all of the others that mess with the strata.

This is with custom level and strata enabled
![Wow_gcscv0MaBE](https://user-images.githubusercontent.com/70599999/112047383-23873580-8b45-11eb-8bb9-882f76dc8270.png) 
This is with it disabled and how i would expect it should function
![Wow_CGxbozuf6B](https://user-images.githubusercontent.com/70599999/112047397-271abc80-8b45-11eb-9e28-8abc625f1ead.png)

**Comment by cont1nuity** [comment]
This is the downside of using UIParent.
You can use the "global scale" on advanced to scale the nameplates instead.
Latest alpha version should improve the borders already.
I'll keep this open to have it on my todo list of things to check for possible improvement.

**Comment by RinZJ** [comment]
Ah okay, ill test out the alpha version but I think I was already using the one with the frame level of borders being bumped by 1 and it didn't seem to change what happened.
Either way its not a massive deal, appreciate the help and hope you can figure something out with it in the future. :)

**Comment by cont1nuity** [comment]
The next alpha version(s) should drastically improve this behavior.

**Comment by RinZJ** [comment]
Thanks, ill give it a try

**Comment by RinZJ** [comment]
Based on very quick test I think this may be exactly what I was looking for. Seems to work exactly like it does when the feature is disabled. Ill leave this open in case i encounter any bugs but so far looks perfect.
Thanks very much.

**Comment by RinZJ** [comment]
One small thing my friend noticed when testing is that the fine tune scale value doesnt save to profile, So when you import a profile with level and strata enabled it leaves it at default 1.41. Is this an issue or intended?

**Comment by cont1nuity** [comment]
Intended.

**Comment by RinZJ** [comment]
Would it in any way be possible to add something like a checkbox to save the scale to profile. I mainly ask as when using fine tune scale and setting the nameplates to be a specific size when someone else imports or i import my own the nameplates end up being massive.
What it looks like normally
![normalPlater](https://user-images.githubusercontent.com/70599999/112386418-c9bf7080-8ce8-11eb-9c32-697a5a69d405.png)
After reimporting the same profile
![scuffedImportPlater](https://user-images.githubusercontent.com/70599999/112386421-ca580700-8ce8-11eb-8792-337d1c41c85a.png)
so you can kinda see why its is an issue.
Not the biggest deal if there is no workaround but would improve this setting a lot.

**Comment by cont1nuity** [comment]
This is not the place. Open a new as feature request ticket if you want to discuss this.

**Comment by RinZJ** [comment]
Apologies will do.

**Comment by cont1nuity** [comment]
This should be resolved with the latest release.
