### ISSUE TITLE
This is causing error when opening Plater config page combined with my UI addon. Can you replace "frame" with "PlaterOptionsPanelFrame" instead?

### ISSUE THREAD

**Issue by ViksUI** [Tercioo/Plater-Nameplates#97]
https://github.com/Tercioo/Plater-Nameplates/blob/a9799e35152d4e1d517de08c2b579e54c2f1ee44/Plater_OptionsPanel.lua#L169

**Comment by ViksUI** [comment]
versionText:SetPoint ("topright", PlaterOptionsPanelFrame, "topright", -25, -7)

This gives no errors for me

**Comment by cont1nuity** [comment]
This will be fixed in an upcoming (alpha) version, but it appears that your UI-Addon is leaking a global `frame` variable.

**Comment by cont1nuity** [comment]
@ViksUI This function causes the issue:
https://github.com/ViksUI/ViksUI/blob/79889f64de6949db7c235d611d0c3812d6072ee6/ViksUI/Modules/UnitFrames/lib.lua#L117
All those functions should not be global, but local to your addon.

**Comment by ViksUI** [comment]
Thank you. Yes you are right about that. I made thos locals and all fixed. The last changes you made to Plater also worked fine.
