### ISSUE TITLE
[Feature] Option to display numbers without being shortened

### ISSUE THREAD

**Issue by karai17** [Tercioo/Plater-Nameplates#98]
I am personally not fond of the abreviated values that a lot of addons offer, no doubt due to retail's excessive number growth over the years. Currently there are only two options in Plater's number formating: Western abreviations and Eastern/Chinese abreviations. If it's not too much to ask, additional options such as showing comma-seperated absolute values would be appreciated.

2.6K (100%) -> 2,588 (100%)

**Comment by karai17** [comment]
Additionally, options to split the value and percentage so that they can be left and right aligned, respectively, rather than both centered together.. but that's a lesser concern.

**Comment by cont1nuity** [comment]
Can be modded and there are mods for this use case on wago.io already.

**Comment by karai17** [comment]
Wouldn't it make more sense to just have these common options available instead of having to seek out additional mods for this.. mod?
