### ISSUE TITLE
[Feature] Enemy Player has no "No Health Bar Shown" options

### ISSUE THREAD

**Issue by karai17** [Tercioo/Plater-Nameplates#99]
On PvE realms, and presumibly in sancuary zones, enemy players are not always pvp flagged and thus not always hostile. In this case, the enemy player's name shows up without a health bar but there are no options to adjust font, size, etc.

**Comment by cont1nuity** [comment]
For retail: Blizzard simply does not provide any nameplates for those units.
For BC: try the latest alpha version and check the advanced tab setting to show healthbars for not attackable units.
The settings may not be exposed, but still can be changed via mods, commands or by copying from a tab where the options are available, e.g. friendly npcs.
I'll consider adding the options.

**Comment by karai17** [comment]
I am on TBC.

I did try copying from Enemy NPC -> Enemy Player but it didn't seem to work.

My intent is to have the health bar hidden if the player is not flagged, but to have a nice font than the default Arial Narrow. I can give the alpha a try and report back though, if you think that may fix it?

**Comment by cont1nuity** [comment]
I suggest joining the Discord to discuss potential solutions.

**Comment by karai17** [comment]
Apparerently I can't talk in that Discord without verifying my phone number so I guess the conversation ends here...

Enemy NPC also has the options which is why I tried copying from there as well.

**Comment by cont1nuity** [comment]
I was mistaken: the name only text size takes the same setting as the usual player name settings.
